<?php
/**********************************************************************************/
/*                                                                                */
/*      Thelia	                                                                  */
/*                                                                                */
/*      Copyright (c) OpenStudio                                                  */
/*      email : info@thelia.net                                                   */
/*      web : http://www.thelia.net                                               */
/*                                                                                */
/*      This program is free software; you can redistribute it and/or modify      */
/*      it under the terms of the GNU General Public License as published by      */
/*      the Free Software Foundation; either version 3 of the License             */
/*                                                                                */
/*      This program is distributed in the hope that it will be useful,           */
/*      but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/*      GNU General Public License for more details.                              */
/*                                                                                */
/*      You should have received a copy of the GNU General Public License         */
/*	    along with this program. If not, see <http://www.gnu.org/licenses/>.      */
/*                                                                                */
/**********************************************************************************/

namespace Thelia\Coupon;

/**
 * Created by JetBrains PhpStorm.
 * Date: 8/19/13
 * Time: 3:24 PM
 *
 * Unit Test BaseFacade Class
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-17 at 18:59:24.
 *
 * @package Coupon
 * @author  Guillaume MOREL <gmorel@openstudio.fr>
 *
 */
class BaseFacadeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCart
     * @todo   Implement testGetCart().
     */
    public function testGetCart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getDeliveryAddress
     * @todo   Implement testGetDeliveryAddress().
     */
    public function testGetDeliveryAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCustomer
     * @todo   Implement testGetCustomer().
     */
    public function testGetCustomer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutTotalPrice
     * @todo   Implement testGetCheckoutTotalPrice().
     */
    public function testGetCheckoutTotalPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutPostagePrice
     * @todo   Implement testGetCheckoutPostagePrice().
     */
    public function testGetCheckoutPostagePrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCartTotalPrice
     * @todo   Implement testGetCartTotalPrice().
     */
    public function testGetCartTotalPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutCurrency
     * @todo   Implement testGetCheckoutCurrency().
     */
    public function testGetCheckoutCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getNbArticlesInCart
     * @todo   Implement testGetNbArticlesInCart().
     */
    public function testGetNbArticlesInCart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCurrentCoupons
     * @todo   Implement testGetCurrentCoupons().
     */
    public function testGetCurrentCoupons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::findOneCouponByCode
     * @todo   Implement testFindOneCouponByCode().
     */
    public function testFindOneCouponByCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getContainer
     * @todo   Implement testGetContainer().
     */
    public function testGetContainer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getTranslator
     * @todo   Implement testGetTranslator().
     */
    public function testGetTranslator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getMainCurrency
     * @todo   Implement testGetMainCurrency().
     */
    public function testGetMainCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getConditionEvaluator
     * @todo   Implement testGetConditionEvaluator().
     */
    public function testGetConditionEvaluator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getAvailableCurrencies
     * @todo   Implement testGetAvailableCurrencies().
     */
    public function testGetAvailableCurrencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getDispatcher
     * @todo   Implement testGetDispatcher().
     */
    public function testGetDispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCartFromTrait
     * @todo   Implement testGetCartFromTrait().
     */
    public function testGetCartFromTrait()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
