<?php
/*************************************************************************************/
/*      This file is part of the Thelia package.                                     */
/*                                                                                   */
/*      Copyright (c) OpenStudio                                                     */
/*      email : dev@thelia.net                                                       */
/*      web : http://www.thelia.net                                                  */
/*                                                                                   */
/*      For the full copyright and license information, please view the LICENSE.txt  */
/*      file that was distributed with this source code.                             */
/*************************************************************************************/

namespace Thelia\Coupon;

/**
 * Unit Test BaseFacade Class
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-17 at 18:59:24.
 *
 * @package Coupon
 * @author  Guillaume MOREL <gmorel@openstudio.fr>
 *
 */
class BaseFacadeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCart
     * @todo   Implement testGetCart().
     */
    public function testGetCart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getDeliveryAddress
     * @todo   Implement testGetDeliveryAddress().
     */
    public function testGetDeliveryAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCustomer
     * @todo   Implement testGetCustomer().
     */
    public function testGetCustomer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutTotalPrice
     * @todo   Implement testGetCheckoutTotalPrice().
     */
    public function testGetCheckoutTotalPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutPostagePrice
     * @todo   Implement testGetCheckoutPostagePrice().
     */
    public function testGetCheckoutPostagePrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCartTotalPrice
     * @todo   Implement testGetCartTotalPrice().
     */
    public function testGetCartTotalPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCheckoutCurrency
     * @todo   Implement testGetCheckoutCurrency().
     */
    public function testGetCheckoutCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getNbArticlesInCart
     * @todo   Implement testGetNbArticlesInCart().
     */
    public function testGetNbArticlesInCart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCurrentCoupons
     * @todo   Implement testGetCurrentCoupons().
     */
    public function testGetCurrentCoupons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::findOneCouponByCode
     * @todo   Implement testFindOneCouponByCode().
     */
    public function testFindOneCouponByCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getContainer
     * @todo   Implement testGetContainer().
     */
    public function testGetContainer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getTranslator
     * @todo   Implement testGetTranslator().
     */
    public function testGetTranslator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getMainCurrency
     * @todo   Implement testGetMainCurrency().
     */
    public function testGetMainCurrency()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getConditionEvaluator
     * @todo   Implement testGetConditionEvaluator().
     */
    public function testGetConditionEvaluator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getAvailableCurrencies
     * @todo   Implement testGetAvailableCurrencies().
     */
    public function testGetAvailableCurrencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getDispatcher
     * @todo   Implement testGetDispatcher().
     */
    public function testGetDispatcher()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Thelia\Coupon\BaseFacade::getCartFromTrait
     * @todo   Implement testGetCartFromTrait().
     */
    public function testGetCartFromTrait()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
