<?php
namespace Thelia\Coupon;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-19 at 18:27:07.
 */
class RuleOrganizerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RuleOrganizer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RuleOrganizer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Thelia\Coupon\RuleOrganizer::organize
     * @todo   Implement testOrganize().
     */
    public function testOrganize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
