<?php

declare(strict_types=1);

/*
 * This file is part of the Thelia package.
 * http://www.thelia.net
 *
 * (c) OpenStudio <info@thelia.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Thelia\Tests\Integration\Core\Routing;

use Propel\Runtime\Propel;
use Thelia\Core\Routing\Rewriting\Exception\UrlRewritingException;
use Thelia\Core\Routing\Rewriting\RewritingResolver;
use Thelia\Core\Routing\Rewriting\RewritingRetriever;
use Thelia\Model\Category;
use Thelia\Model\RewritingUrlQuery;
use Thelia\Test\IntegrationTestCase;

final class UrlRewritingTest extends IntegrationTestCase
{
    private function createCategoryWithTitle(string $title): Category
    {
        $factory = $this->createFixtureFactory();
        $category = $factory->category();
        $category->setLocale('en_US')->setTitle($title)->save();

        return $category;
    }

    public function testGenerateRewrittenUrlCreatesSlugFromTitle(): void
    {
        $category = $this->createCategoryWithTitle('Summer Collection');

        $con = Propel::getConnection('TheliaMain');
        $url = $category->generateRewrittenUrl('en_US', $con);

        self::assertStringEndsWith('.html', $url);
        self::assertStringContainsString('summer-collection', $url);
    }

    public function testGetRewrittenUrlReturnsAutoGeneratedUrl(): void
    {
        // Setting a title and saving auto-generates the rewritten URL
        // via a Propel postInsert/postUpdate hook.
        $category = $this->createCategoryWithTitle('Winter Sale');

        $retrieved = $category->getRewrittenUrl('en_US');
        self::assertNotNull($retrieved);
        self::assertStringContainsString('winter-sale', $retrieved);
    }

    public function testGenerateRewrittenUrlHandlesCollisions(): void
    {
        $con = Propel::getConnection('TheliaMain');

        $cat1 = $this->createCategoryWithTitle('Duplicate Title');
        $url1 = $cat1->generateRewrittenUrl('en_US', $con);

        $cat2 = $this->createCategoryWithTitle('Duplicate Title');
        $url2 = $cat2->generateRewrittenUrl('en_US', $con);

        self::assertNotSame($url1, $url2);
        self::assertMatchesRegularExpression('/duplicate-title(-\d+)?\.html/', $url1);
        self::assertMatchesRegularExpression('/duplicate-title-\d+\.html/', $url2);
    }

    public function testRewritingResolverResolvesGeneratedUrl(): void
    {
        $category = $this->createCategoryWithTitle('Resolvable Category');

        $con = Propel::getConnection('TheliaMain');
        $url = $category->generateRewrittenUrl('en_US', $con);

        $resolver = new RewritingResolver($url);

        self::assertSame('category', $resolver->view);
        self::assertSame((string) $category->getId(), $resolver->viewId);
        self::assertSame('en_US', $resolver->locale);
    }

    public function testRewritingResolverThrowsForUnknownUrl(): void
    {
        $this->expectException(UrlRewritingException::class);
        new RewritingResolver('this-url-does-not-exist-'.uniqid().'.html');
    }

    public function testRewritingRetrieverFindsUrlForView(): void
    {
        $factory = $this->createFixtureFactory();
        $brand = $factory->brand(['title' => 'Retrievable Brand']);

        $con = Propel::getConnection('TheliaMain');
        $brand->generateRewrittenUrl('en_US', $con);

        $retriever = new RewritingRetriever();
        $retriever->loadViewUrl('brand', 'en_US', $brand->getId());

        self::assertNotNull($retriever->rewrittenUrl);
        self::assertStringContainsString('retrievable-brand', $retriever->rewrittenUrl);
    }

    public function testRewritingRetrieverReturnsNullForMissingUrl(): void
    {
        $retriever = new RewritingRetriever();
        $retriever->loadViewUrl('brand', 'en_US', 999999);

        self::assertNull($retriever->rewrittenUrl);
        self::assertNotNull($retriever->url);
    }

    public function testProductRewrittenUrlRoundTrip(): void
    {
        $factory = $this->createFixtureFactory();
        $product = $factory->product(
            $factory->category(),
            $factory->taxRule(),
            $factory->currency(),
        );
        $product->setLocale('en_US')->setTitle('Amazing Widget')->save();

        $con = Propel::getConnection('TheliaMain');
        $url = $product->generateRewrittenUrl('en_US', $con);

        self::assertStringContainsString('amazing-widget', $url);

        $resolver = new RewritingResolver($url);
        self::assertSame('product', $resolver->view);
        self::assertSame((string) $product->getId(), $resolver->viewId);
    }

    public function testGetRewrittenUrlReturnsNullForCategoryWithoutTitle(): void
    {
        $factory = $this->createFixtureFactory();
        $category = $factory->category();

        // No title was set, so no URL was auto-generated.
        self::assertNull($category->getRewrittenUrl('en_US'));
    }

    public function testRewritingUrlIsRemovedOnDelete(): void
    {
        $category = $this->createCategoryWithTitle('Deletable Category');

        $con = Propel::getConnection('TheliaMain');
        $category->generateRewrittenUrl('en_US', $con);

        $count = RewritingUrlQuery::create()
            ->filterByView('category')
            ->filterByViewId($category->getId())
            ->count();
        self::assertGreaterThan(0, $count);

        $category->delete();

        $countAfter = RewritingUrlQuery::create()
            ->filterByView('category')
            ->filterByViewId($category->getId())
            ->count();
        self::assertSame(0, $countAfter);
    }
}
