framework:
    default_locale: en_US
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths: ['%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/translations']
        fallbacks:
            - fr_FR
        providers:
