twig:
  file_name_pattern: "*.twig"
  paths:
    "%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/components": components
    "%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/react-components": react
    "%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/assets": assets
    "%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/form": formTwig
  form_themes:
    - "frontOffice/%thelia_front_template%/form/fields.html.twig"

when@test:
  twig:
    strict_variables: true
