twig_component:
  anonymous_template_directory: 'frontOffice/%thelia_front_template%/components/'
  defaults:
    # Namespace & directory for components
    FlexyBundle\Twig\:
      template_directory: 'frontOffice/%thelia_front_template%/twig-components/'
      name_prefix: Flexy
