ux_translator:
    # The directory where the JavaScript translations are dumped
    dump_directory: '%kernel.project_dir%/templates/frontOffice/%thelia_front_template%/translations/compiled'
    domains: [messages]
