/admin
/admin/home
/admin/latest-thelia-version
/admin/home/stats
/admin/ajax/thelia_news_feed
/admin/login
/admin/logout
/admin/checklogin
/admin/catalog
/admin/image/type/{parentType}/{parentId}/save-ajax
/admin/image/type/{parentType}/{parentId}/form-ajax
/admin/image/type/{parentType}/{parentId}/list-ajax
/admin/image/type/{parentType}/{parentId}/update-position
/admin/image/type/{parentType}/{documentId}/toggle
/admin/image/type/{parentType}/{imageId}/update
/admin/image/type/{parentType}/{imageId}/update
/admin/image/type/{parentType}/delete/{imageId}
/admin/document/type/{parentType}/{parentId}/save-ajax
/admin/document/type/{parentType}/{parentId}/form-ajax
/admin/document/type/{parentType}/{parentId}/list-ajax
/admin/document/type/{parentType}/{parentId}/update-position
/admin/document/type/{parentType}/{documentId}/toggle
/admin/document/type/{parentType}/{documentId}/update
/admin/document/type/{parentType}/{documentId}/update
/admin/document/type/{parentType}/delete/{documentId}
/admin/customers
/admin/customer/update
/admin/customer/save
/admin/customer/delete
/admin/customer/create
/admin/address/delete
/admin/address/use
/admin/address/create
/admin/address/update
/admin/address/save
/admin/orders
/admin/order/update/{order_id}
/admin/order/update/status
/admin/order/update/{order_id}/status
/admin/order/update/{order_id}/delivery-ref
/admin/order/update/{order_id}/address
/admin/order/pdf/invoice/{order_id}
/admin/order/pdf/delivery/{order_id}
/admin/categories
/admin/categories/create
/admin/categories/update
/admin/categories/save
/admin/categories/seo/save
/admin/categories/toggle-online
/admin/categories/delete
/admin/categories/update-position
/admin/categories/related-content/add
/admin/categories/related-picture/add
/admin/categories/related-content/delete
/admin/category/{categoryId}/available-related-content/{folderId}.{_format}
/admin/catalog/category/parent/{parentId}.{_format}
/admin/products
/admin/products/create
/admin/products/update
/admin/products/save
/admin/products/seo/save
/admin/products/toggle-online
/admin/products/delete
/admin/products/update-position
/admin/products/general/tab
/admin/products/related/tab
/admin/products/category/add
/admin/products/category/delete
/admin/products/content/add
/admin/products/content/delete
/admin/product/{productId}/available-content/{folderId}.{_format}
/admin/product/update-content-position
/admin/product/calculate-price
/admin/product/calculate-raw-price
/admin/product/load-converted-prices
/admin/products/accessory/add
/admin/products/accessory/delete
/admin/product/{productId}/available-accessories/{categoryId}.{_format}
/admin/product/update-accessory-position
/admin/products/attributes/tab
/admin/product/{productId}/set-product-template
/admin/product/{productId}/update-attributes-and-features
/admin/product/{productId}/attribute-values/{attributeId}.{_format}
/admin/product/{productId}/add-attribute-value-to-combination/{attributeAvId}/{combination}.{_format}
/admin/product/combination/add
/admin/product/combination/delete
/admin/product/combinations/update
/admin/product/combination/build
/admin/product/default-price/update
/admin/product_sale_elements/{pseId}/{type}/{typeId}
/admin/product_sale_elements/ajax/{type}/{id}
/admin/product/virtual-documents/{productId}/{pseId}
/admin/folders
/admin/folders/create
/admin/folders/update/{folder_id}
/admin/folders/toggle-online
/admin/folders/save
/admin/folders/seo/save
/admin/folders/delete
/admin/folders/update-position
/admin/content/create
/admin/content/update/{content_id}
/admin/content/save
/admin/content/seo/save
/admin/content/update-position
/admin/content/toggle-online
/admin/content/delete
/admin/content/folder/add
/admin/content/folder/delete
/admin/coupon
/admin/coupon/create
/admin/coupon/update/{couponId}
/admin/coupon/draw/inputs/{couponServiceId}
/admin/coupon/draw/conditionsSummaries/{couponId}
/admin/coupon/draw/read/conditionInputs/{conditionId}
/admin/coupon/draw/update/conditionInputs/{couponId}/{conditionIndex}
/admin/coupon/{couponId}/condition/save
/admin/coupon/{couponId}/condition/delete/{conditionIndex}
/admin/coupon/consume/{couponCode}
/admin/configuration
/admin/configuration/variables
/admin/configuration/variables/update-values
/admin/configuration/variables/create
/admin/configuration/variables/update
/admin/configuration/variables/save
/admin/configuration/variables/delete
/admin/configuration/store
/admin/configuration/store/save
/admin/configuration/system-logs
/admin/configuration/system-logs/save
/admin/configuration/messages
/admin/configuration/messages/create
/admin/configuration/messages/update
/admin/configuration/messages/save
/admin/configuration/messages/delete
/admin/configuration/currencies
/admin/configuration/currencies/create
/admin/configuration/currencies/update
/admin/configuration/currencies/save
/admin/configuration/currencies/set-default
/admin/configuration/currencies/update-position
/admin/configuration/currencies/update-rates
/admin/configuration/currencies/delete
/admin/configuration/currencies/update-position
/admin/configuration/templates
/admin/configuration/templates/create
/admin/configuration/templates/update
/admin/configuration/templates/save
/admin/configuration/templates/delete
/admin/configuration/templates/features/list
/admin/configuration/templates/features/add
/admin/configuration/templates/features/delete
/admin/template/update-feature-position
/admin/configuration/templates/attributes/list
/admin/configuration/templates/attributes/add
/admin/configuration/templates/attributes/delete
/admin/template/update-attribute-position
/admin/configuration/attributes
/admin/configuration/attributes/create
/admin/configuration/attributes/update
/admin/configuration/attributes/save
/admin/configuration/attributes/delete
/admin/configuration/attributes/update-position
/admin/configuration/attributes/remove-from-all-templates
/admin/configuration/attributes/add-to-all-templates
/admin/configuration/attributes-av/create
/admin/configuration/attributes-av/update
/admin/configuration/attributes-av/save
/admin/configuration/attributes-av/delete
/admin/configuration/attributes-av/update-position
/admin/configuration/shipping_zones
/admin/configuration/shipping_zones/update/{delivery_module_id}
/admin/configuration/shipping_zones/area/add
/admin/configuration/shipping_zones/area/remove
/admin/configuration/shipping_configuration
/admin/configuration/shipping_configuration/update/{area_id}
/admin/configuration/shipping_configuration/delete
/admin/configuration/shipping_configuration/create
/admin/configuration/shipping_configuration/update_postage/{area_id}
/admin/configuration/shipping_configuration/country/add
/admin/configuration/shipping_configuration/country/remove
/admin/configuration/countries
/admin/configuration/countries/create
/admin/configuration/country/update/{country_id}
/admin/configuration/country/save/{country_id}
/admin/configuration/countries/delete
/admin/configuration/country/toggleDefault
/admin/configuration/profiles
/admin/configuration/profiles/update/{profile_id}
/admin/configuration/profiles/add
/admin/configuration/profiles/save
/admin/configuration/profiles/saveResourceAccess
/admin/configuration/profiles/saveModuleAccess
/admin/configuration/profiles/delete
/admin/configuration/administrators
/admin/configuration/administrators/add
/admin/configuration/administrators/save
/admin/configuration/administrators/delete
/admin/configuration/mailingSystem
/admin/configuration/mailingSystem/save
/admin/configuration/mailingSystem/test
/admin/configuration/adminLogs
/admin/configuration/adminLogs/logger
/admin/configuration/features
/admin/configuration/features/create
/admin/configuration/features/update
/admin/configuration/features/save
/admin/configuration/features/delete
/admin/configuration/features/update-position
/admin/configuration/features/remove-from-all-templates
/admin/configuration/features/add-to-all-templates
/admin/configuration/features-av/create
/admin/configuration/features-av/update
/admin/configuration/features-av/save
/admin/configuration/features-av/delete
/admin/configuration/features-av/update-position
/admin/configuration/advanced
/admin/configuration/advanced/flush-cache
/admin/configuration/advanced/flush-assets
/admin/configuration/advanced/flush-images-and-documents
/admin/modules
/admin/module/update/{module_id}
/admin/module/save
/admin/module/toggle-activation/{module_id}
/admin/module/delete
/admin/module/update-position
/admin/module/{module_code}
/admin/hooks
/admin/hooks/discover
/admin/hooks/discover/save
/admin/hooks/create
/admin/hook/update/{hook_id}
/admin/hook/save/{hook_id}
/admin/hooks/delete
/admin/hook/toggle-activation
/admin/hook/toggle-native
/admin/module-hooks
/admin/module-hooks/create
/admin/module-hook/update/{module_hook_id}
/admin/module-hook/save/{module_hook_id}
/admin/module-hooks/delete
/admin/module-hooks/toggle-activation/{module_hook_id}
/admin/module-hooks/update-position
/admin/configuration/taxes/update/{tax_id}
/admin/configuration/taxes/add
/admin/configuration/taxes/save
/admin/configuration/taxes/delete
/admin/configuration/taxes_rules
/admin/configuration/taxes_rules/update/{tax_rule_id}
/admin/configuration/taxes_rules/add
/admin/configuration/taxes_rules/save
/admin/configuration/taxes_rules/saveTaxes
/admin/configuration/taxes_rules/delete
/admin/configuration/taxes_rules/update/set_default/{tax_rule_id}
/admin/configuration/languages
/admin/configuration/languages/update/{lang_id}
/admin/configuration/languages/save/{lang_id}
/admin/configuration/languages/toggleDefault/{lang_id}
/admin/configuration/languages/add
/admin/configuration/languages/delete
/admin/configuration/languages/defaultBehavior
/admin/configuration/languages/updateUrl
/admin/configuration/languages/domain/activate
/admin/configuration/languages/domain/deactivate
/admin/configuration/translations
/admin/configuration/translations/update
/admin/brand
/admin/brand/create
/admin/brand/update/{brand_id}
/admin/brand/save/{brand_id}
/admin/brand/seo/save
/admin/brand/toggle-online
/admin/brand/update-position
/admin/brand/delete
/admin/export
/admin/export/position
/admin/export/position/category
/admin/export/{id}
/admin/export/{id}
/admin/import
/admin/import/position
/admin/import/position/category
/admin/import/{id}
/admin/import/{id}
/admin/sales
/admin/sales/reset
/admin/sales/check-activation
/admin/sale/create
/admin/sale/update/{sale_id}
/admin/sale/save/{sale_id}
/admin/sale/delete
/admin/sale/update-product-list/{sale_id}
/admin/sale/update-product-attribute-list/{sale_id}/{product_id}
/admin/sale/toggle-activity/{sale_id}
/admin/{template}
