#!/bin/bash

php-cs-fixer fix core/lib/Thelia/Action/ --level=all
php-cs-fixer fix core/lib/Thelia/Cart/ --level=all
php-cs-fixer fix core/lib/Thelia/Command/ --level=all
php-cs-fixer fix core/lib/Thelia/Condition/ --level=all
php-cs-fixer fix core/lib/Thelia/Config/ --level=all
php-cs-fixer fix core/lib/Thelia/Controller/ --level=all
php-cs-fixer fix core/lib/Thelia/Core/ --level=all
php-cs-fixer fix core/lib/Thelia/Coupon/ --level=all
php-cs-fixer fix core/lib/Thelia/Exception/ --level=all
php-cs-fixer fix core/lib/Thelia/Form/ --level=all
php-cs-fixer fix core/lib/Thelia/Install/ --level=all
php-cs-fixer fix core/lib/Thelia/Log/ --level=all
php-cs-fixer fix core/lib/Thelia/Mailer/ --level=all
find core/lib/Thelia/Model/ -maxdepth 1 -name  *.php -exec php-cs-fixer fix '{}' --level=all  \;
php-cs-fixer fix core/lib/Thelia/Model/Exception --level=all
php-cs-fixer fix core/lib/Thelia/Model/Tools --level=all
php-cs-fixer fix core/lib/Thelia/Module/ --level=all
php-cs-fixer fix core/lib/Thelia/Rewriting/ --level=all
php-cs-fixer fix core/lib/Thelia/TaxEngine/ --level=all
php-cs-fixer fix core/lib/Thelia/Tests --level=all
php-cs-fixer fix core/lib/Thelia/Tools/ --level=all
php-cs-fixer fix core/lib/Thelia/Type/ --level=all