#!/usr/bin/env php
<?php

set_time_limit(0);

require __DIR__ . '/core/bootstrap.php';

use Thelia\Core\Thelia;
use Thelia\Core\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$thelia = new Thelia($env, $debug);
$application = new Application($thelia);
$application->run($input);