import getLocale from '@utils/getLocale';

export const locale = getLocale();

const messages = {
  'fr-FR': {
    OK: 'OK',
    SUBMIT: 'Valider',
    SELECT: 'Sélectionner',
    DELETE: 'Supprimer',
    EDIT: 'Éditer',
    CREATE_ADDRESS: 'Créer une adresse',
    EDIT_AN_ADDRESS: 'Éditer une adresse',
    CLOSE: 'Fermer',
    CHOOSE: 'Choisir',
    UNDERSTOOD: "J'ai compris",
    YOUR_ORDER: 'Votre commande',
    CHOOSE_DELIVERY_MODE: 'Choisir mon mode de livraison',
    HOME_DELIVERY: 'Livraison à domicile',
    PICKUP_DELIVERY: 'Livraison en point relais',
    CHOOSE_DELIVERY_ADDRESS: 'Choisir mon adresse de livraison',
    CHOOSE_BILLING_ADDRESS: 'Choisir mon adresse de facturation',
    CHOOSE_DELIVERY_PROVIDER: 'Choisir mon service de livraison',
    PAYMENT_MODE: 'Mode de paiement',
    BILLING_ADDRESS: 'Adresse de facturation',
    VALIDATE_CHECKOUT: 'Valider ma commande',
    TOTAL_UNTAXED: 'Total HT',
    DELIVERY: 'Livraison à domicile',
    DELIVERY_GENERAL: 'Livraison',
    BILLING: 'Facturation',
    COMMENTS: 'Commentaire',
    PAYMENT: 'Paiement',
    TAXES: 'TVA & taxes',
    DISCOUNT: 'Réduction',
    TOTAL: 'Total TTC',
    CART_EMPTY: 'Votre panier est vide',
    CHOOSE_ADDRESS: 'Choisir cette adresse',
    DEFAULT_ADDRESS: 'Adresse par défaut',
    OTHER_ADDRESS: 'Autre adresse ?',
    SAME_ADDRESS: "Identique à l'adresse de livraison",
    SELECT_BILLING_ADDRESS: 'Sélectionnez une adresse de facturation',
    SELECT_DELIVERY_ADDRESS: 'Sélectionnez une adresse de livraison',
    TELEPHONE_CHECK: 'Vérification de votre numéro de téléphone',
    CHOOSE_MODULE: 'Choisir un module de livraison',
    ADD_COMMENT: 'Ajouter un commentaire à votre commande',
    YOUR_COMMENT: 'Votre commentaire',
    DELIVERY_AND_BELLING: 'Livraison et facturation',
    IGNORE: 'Ignorer',
    NO_COMMENT: 'Pas de commentaire',
    ACCEPT_CGV: 'Accepter les conditions générales de vente',
    NO_RELAY_POINT: 'Aucun point relais disponible',
    ADD_TO_CART: 'Ajouter au panier',
    ERROR_ADD_CART: "Erreur lors de l'ajour au panier",
    PRODUCT_UNAVAILABLE: 'Produit indisponible',
    HELLO: 'Bonjour',
    ACCOUNT: 'Mon profil',
    MY_ORDERS: 'Mes commandes',
    MY_ADDRESSES: 'Mes adresses',
    DECONNECTION: 'Me déconnecter',
    LOGIN: 'Me connecter',
    NEW_CUSTOMER: 'Nouveau client',
    ALREADY_CUSTOMER: 'Déjà client ?',
    CREATE_ACCOUNT: 'Créer un compte',
    SUBMIT_CART: 'Valider le panier',
    COUPON: 'Code promo',
    MANDATORY: 'Requis',
    PASSWORD: 'Mot de passe',
    EMAIL: 'E-mail',
    QUANTITY: 'quantité',
    PICKUP: 'Livraison en point relais',
    FREE: 'Offert',
    FORGET_PASSWORD: 'Mot de passe oublié',
    LABEL_LABEL: 'Libellé',
    CIVILITY_TITLE_LABEL: 'Titre',
    FIRSTNAME_LABEL: 'Prénom',
    LASTNAME_LABEL: 'Nom',
    COMPANY_LABEL: 'Société',
    ADDRESS_1_LABEL: 'Adresse',
    ADDRESS_2_LABEL: 'Adresse suite',
    ADDRESS_3_LABEL: 'Adresse fin',
    ZIPCODE_LABEL: 'Code postal',
    CITY_LABEL: 'Ville',
    COUNTRY_LABEL: 'Pays',
    CELLPHONE_LABEL: 'Numéro de portable',
    PHONE_LABEL: 'Téléphone',
    WARNING: 'Attention',
    NO_PAYMENT_MODE_AVAILABLE: "Aucun moyen de paiement n'est disponible",
    NO_DELIVERY_MODE_AVAILABLE: "Aucun moyen de livraison n'est disponible",
    FIND_RELAY: 'Trouver un point relais',
    INCORRECT_ZIPCODE: 'Le code postal est incorrect'
  },
  'en-US': {
    OK: 'OK',
    SUBMIT: 'Submit',
    SELECT: 'Select',
    DELETE: 'Delete',
    EDIT: 'Edit',
    CREATE_ADDRESS: 'Create an address',
    EDIT_AN_ADDRESS: 'Edit an address',
    CLOSE: 'Close',
    CHOOSE: 'Choose',
    TOTAL_UNTAXED: 'Total w/o tax',
    CHOOSE_DELIVERY_MODE: 'Choose delivery mode',
    HOME_DELIVERY: 'Delivery',
    PICKUP_DELIVERY: 'Pickup',
    CHOOSE_DELIVERY_ADDRESS: 'Choose your delivery address',
    CHOOSE_BILLING_ADDRESS: 'Choose your billing address',
    CHOOSE_DELIVERY_PROVIDER: 'Choose your delivery provider',
    PAYMENT_MODE: 'Payment mode',
    BILLING_ADDRESS: 'Billing address',
    VALIDATE_CHECKOUT: 'Validate my order',
    DELIVERY: 'Home delivery',
    DELIVERY_GENERAL: 'Delivery',
    BILLING: 'Billing',
    COMMENTS: 'Comment',
    PAYMENT: 'Payment',
    TAXES: 'Taxes',
    DISCOUNT: 'Discount',
    TOTAL: 'Total w/ taxes',
    CART_EMPTY: 'Your cart is empty',
    CHOOSE_ADDRESS: 'Choose this address',
    DEFAULT_ADDRESS: 'Default address',
    OTHER_ADDRESS: 'Another address ?',
    SAME_ADDRESS: 'Same as delivery address',
    SELECT_BILLING_ADDRESS: 'Select billing address',
    SELECT_DELIVERY_ADDRESS: 'Select delivery address',
    TELEPHONE_CHECK: 'Verify your phone number',
    CHOOSE_MODULE: 'choose a delivery module',
    ADD_COMMENT: 'Add comment to your order',
    YOUR_COMMENT: 'Your comment',
    DELIVERY_AND_BELLING: 'delivery and billing',
    IGNORE: 'Ignore',
    NO_COMMENT: 'no comment',
    ACCEPT_CGV: 'I accept the Terms of Conditions',
    NO_RELAY_POINT: 'No relay point available',
    ADD_TO_CART: 'add to cart',
    ERROR_ADD_CART: 'Cannot add this product to your cart',
    PRODUCT_UNAVAILABLE: 'Unavailable product',
    HELLO: 'Hello',
    ACCOUNT: 'My Account',
    MY_ORDERS: 'My orders',
    MY_ADDRESSES: 'My addresses',
    DECONNECTION: 'Deconnection',
    LOGIN: 'Login',
    NEW_CUSTOMER: 'New customer',
    ALREADY_CUSTOMER: 'Already customer ?',
    CREATE_ACCOUNT: 'Create account',
    SUBMIT_CART: 'Submit cart',
    COUPON: 'Coupon',
    MANDATORY: 'MANDATORY',
    PASSWORD: 'Password',
    EMAIL: 'E-mail',
    QUANTITY: 'quantity',
    PICKUP: 'Pickup delivery',
    FREE: 'Free',
    FORGET_PASSWORD: 'I forgot my password',
    LOADING: 'Loading',
    YOUR_ORDER: 'Your order',
    LABEL_LABEL: 'Label',
    CIVILITY_TITLE_LABEL: 'Title',
    FIRSTNAME_LABEL: 'Firstname',
    LASTNAME_LABEL: 'Name',
    COMPANY_LABEL: 'Company',
    ADDRESS_1_LABEL: 'Address',
    ADDRESS_2_LABEL: 'Address next',
    ADDRESS_3_LABEL: 'Address end',
    ZIPCODE_LABEL: 'Zip code',
    CITY_LABEL: 'City',
    COUNTRY_LABEL: 'Country',
    CELLPHONE_LABEL: 'Cellphone',
    PHONE_LABEL: 'Phone',
    WARNING: 'Warning',
    NO_PAYMENT_MODE_AVAILABLE: 'No payment mode available',
    NO_DELIVERY_MODE_AVAILABLE: 'No delivery mode available',
    FIND_RELAY: 'Find a relay point',
    INCORRECT_ZIPCODE: 'Zipcode is incorrect'
  }
};

export default messages;
