<?php
/* File generated by \Thelia\Config\Dumper\TpexConfigDumper */
class TpexConfig
{

    public function getLoopConfig()
    {
        return array();
    }

    public function getFilterConfig()
    {
        return array();
    }

    public function getBaseParamConfig()
    {
        return array();
    }

    public function getLoopTestConfig()
    {
        return array();
    }
}