# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: 'gd'
  resolvers:
    default:
      web_path:
        web_root: '%kernel.project_dir%/public'
        cache_prefix: 'cache/images'

  loaders:
    default:
      filesystem:
        data_root: '%kernel.project_dir%/local/media/images'

  filter_sets:
    default:
    add_to_cart:
    order_card:
    order_card_detail:
