<?php
/*************************************************************************************/
/*      This file is part of the Thelia package.                                     */
/*                                                                                   */
/*      Copyright (c) OpenStudio                                                     */
/*      email : dev@thelia.net                                                       */
/*      web : http://www.thelia.net                                                  */
/*                                                                                   */
/*      For the full copyright and license information, please view the LICENSE.txt  */
/*      file that was distributed with this source code.                             */
/*************************************************************************************/

namespace Thelia\Core\Hook;

use Symfony\Component\Locale\Locale;
use Symfony\Component\Translation\TranslatorInterface;
use Thelia\Core\HttpFoundation\Request;
use Thelia\Core\HttpFoundation\Session\Session;
use Thelia\Core\Template\Assets\AssetManagerInterface;
use Thelia\Core\Template\Smarty\Assets\SmartyAssetsManager;
use Thelia\Core\Template\Smarty\SmartyParser;
use Thelia\Core\Template\TemplateDefinition;
use Thelia\Model\Cart;
use Thelia\Model\ConfigQuery;
use Thelia\Model\Currency;
use Thelia\Model\Customer;
use Thelia\Model\Lang;
use Thelia\Module\BaseModule;

/**
 * The base class for hook. If you provide hooks in your module you have to extends
 * this class.
 *
 * These class provides some helper functions to retrieve object from the current session
 * of the current user. It also provides a render function that allows you to get the right
 * template file from different locations and allows you to override templates in your current
 * template.
 *
 * Class BaseHook
 * @package Thelia\Core\Hook
 * @author Julien Chanséaume <jchanseaume@openstudio.fr>
 */
abstract class BaseHook
{
    /**
     * @var BaseModule
     */
    public $module = null;

    /**
     * @var SmartyParser
     */
    public $parser = null;

    /** @var TranslatorInterface $translator */
    public $translator = null;

    /** @var AssetManagerInterface $assetManager */
    public $assetsManager = null;

    protected $assetManager = null;

    /** @var Request $request */
    protected $request = null;


    /** @var Session $session */
    protected $session = null;

    /** @var Customer $customer */
    protected $customer = null;

    /** @var Cart $cart */
    protected $cart = null;

    /** @var Lang $lang */
    protected $lang = null;

    /** @var Currency $currency */
    protected $currency = null;

    /**
     * helper function allowing you to render a template using smarty
     *
     * @param  string $templateName the template path of the template
     * @param  array  $parameters   an array of parameters to assign to smarty
     * @return string the content generated by smarty
     */
    public function render($templateName, array $parameters = array())
    {
        $templatePath = $this->resolvePath($templateName);

        $content = "";
        if (null !== $templatePath) {
            // retrieve the template
            $smartyParser = $this->parser;
            $content = $smartyParser->render($templatePath, $parameters);
        } else {
            $content = sprintf("ERR: Unknown template %s for module %s", $templateName, $this->module->getCode());
        }

        return $content;
    }

    /**
     * helper function allowing you to get the content of a file
     *
     * @param  string $fileName     the template path of the template
     * @return string               the content of the file
     */
    public function dump($fileName)
    {
        $filePath = $this->resolvePath($fileName);

        $content = "";
        if (null !== $filePath) {
            $content = file_get_contents($filePath);
            if (false === $content){
                $content = "";
            }
        } else {
            $content = sprintf("ERR: Unknown file %s for module %s", $fileName, $this->module->getCode());
        }

        return $content;
    }

    /**
     * @return null|SmartyAssetsManager
     */
    protected function getAssetManager()
    {
        if (null === $this->assetManager){
            $asset_dir_from_web_root = ConfigQuery::read('asset_dir_from_web_root', 'assets');
            $this->assetManager = new SmartyAssetsManager($this->assetsManager, THELIA_WEB_DIR, $asset_dir_from_web_root);
        }
        return $this->assetManager;
    }

    /**
     * helper function allowing you to generate the HTML style tag
     *
     * @param  string $fileName     the path to the css file
     * @param array   $attributes   the attributes of the tag
     * @return string               the style tag
     */
    public function addCSS($fileName, $attributes=array())
    {
        $tag = "";
        /*
        $fileURL = $this->getAssetManager()->computeAssetUrl(
            'css',
            array(
                'file'   => $fileName,
                'source' => $this->getModule()->getCode()
            ),
            $this->parser);
        */

        $url = $this->assetsManager->processAsset(
            $assetSource . DS . $file,
            $assetSource . DS . self::$assetsDirectory,
            $this->web_root . $this->path_relative_to_web_root,
            $templateDefinition->getPath(),
            $assetOrigin,
            URL::getInstance()->absoluteUrl($this->path_relative_to_web_root, null, URL::PATH_TO_FILE /* path only */),
            $assetType,
            $filters,
            $debug
        );

        if ("" !== $fileURL){
            $tags = array();
            $tags[] = "<link rel='stylesheet' type='text/css' ";
            $tags[] = " href='" . $fileURL . "' ";
            foreach ($attributes as $name => $val){
                if (is_string($name) && ! in_array($name, array("href", "rel", "type"))){
                    $tags[] = $name . "='" . $val . "' ";
                }
            }
            $tags[] = "/>";
            $tag = implode($tags);
        }

        return $tag;
    }


    /**
     * Resolve the file path.
     *
     * A system of fallback enables file overriding. It will look for the template :
     *      - in the current template in directory /modules/{module code}/
     *      - in the module in the current template if it exists
     *      - in the module in the default template

     * @param $fileName     the filename
     * @return mixed        the resolved file path
     */
    protected function resolvePath($fileName)
    {
        $filePath = null;

        // retrieve the template
        $smartyParser = $this->parser;

        // First look into the current template in the right scope : frontOffice, backOffice, ...
        // template should be overrided in : {template_path}/modules/{module_code}/{template_name}
        /** @var \Thelia\Core\Template\Smarty\SmartyParser $templateDefinition */
        $templateDefinition = $smartyParser->getTemplateDefinition(false);
        $templateDirectories = $smartyParser->getTemplateDirectories($templateDefinition->getType());

        if (isset($templateDirectories[$templateDefinition->getName()]["0"])) {
            $filePath = $templateDirectories[$templateDefinition->getName()]["0"]
                . DS . TemplateDefinition::HOOK_OVERRIDE_SUBDIR
                . DS . $this->module->getCode()
                . DS . $fileName;
            if (! file_exists($filePath)) {
                $filePath = null;
            }
        }

        // If the smarty template doesn't exist, we try to see if there is an
        // implementation for the template used in the module directory
        if (null === $filePath) {
            if (isset($templateDirectories[$templateDefinition->getName()][$this->module->getCode()])) {
                $filePath = $templateDirectories[$templateDefinition->getName()][$this->module->getCode()]
                    . DS . $fileName;
                if (! file_exists($filePath)) {
                    $filePath = null;
                }
            }
        }

        // Not here, we finally try to fallback on the default theme in the module
        if (null === $filePath && $templateDefinition->getName() !== TemplateDefinition::HOOK_DEFAULT_THEME) {
            if ($templateDirectories[TemplateDefinition::HOOK_DEFAULT_THEME]
                && isset($templateDirectories[TemplateDefinition::HOOK_DEFAULT_THEME][$this->module->getCode()])) {
                $filePath = $templateDirectories[TemplateDefinition::HOOK_DEFAULT_THEME][$this->module->getCode()]
                    . DS . $fileName;
                if (! file_exists($filePath)) {
                    $filePath = null;
                }
            }
        }

        return $fileName;
    }


    /**
     * @param \Thelia\Module\BaseModule $module
     */
    public function setModule($module)
    {
        $this->module = $module;
    }

    /**
     * @return \Thelia\Module\BaseModule
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * @param \Thelia\Core\Template\Smarty\SmartyParser $parser
     */
    public function setParser($parser)
    {
        $this->parser = $parser;
    }

    /**
     * @return \Thelia\Core\Template\Smarty\SmartyParser
     */
    public function getParser()
    {
        return $this->parser;
    }

    /**
     * Translates the given message.
     *
     * @param string $id         The message id (may also be an object that can be cast to string)
     * @param array  $parameters An array of parameters for the message
     * @param string $domain     The domain for the message
     * @param string $locale     The locale
     *
     * @return string The translated string
     *
     * @api
     */
    protected function trans($id, array $parameters = array(), $domain = null, $locale = null)
    {
        return $this->translator->trans($id, $parameters, $domain, $locale);
    }

    /**
     * get the request
     *
     * @return Request
     */
    protected function getRequest()
    {
        if (null === $this->request) {
            $this->request = $this->getParser()->getRequest();
        }

        return $this->request;
    }

    /**
     * get the session
     *
     * @return Session
     */
    protected function getSession()
    {
        if (null === $this->session) {
            if (null !== $this->getRequest()) {
                $this->session = $this->request->getSession();
            }
        }

        return $this->session;
    }

    /**
     * Get the view argument for the request.
     *
     * It allows you to identify the page currently displayed. eg: index, category, ...
     *
     * @return string the current view
     */
    protected function getView()
    {
        $ret = "";
        if (null !== $this->getRequest()) {
            $ret = $this->getRequest()->attributes->get("_view", "");
        }

        return $ret;
    }

    /**
     * Get the cart from the session
     *
     * @return \Thelia\Model\Cart|null
     */
    protected function getCart()
    {
        if (null === $this->cart) {
            $this->cart = $this->getSession() ? $this->getSession()->getCart() : null;
        }

        return $this->cart;
    }

    /**
     * Get the current currency used or if not present the default currency for the shop
     *
     * @return \Thelia\Model\Currency
     */
    protected function getCurrency()
    {
        if (null === $this->currency) {
            $this->currency = $this->getSession() ? $this->getSession()->getCurrency(true) : null;
        }
        if (null === $this->currency) {
            $this->currency = Currency::getDefaultCurrency();
        }

        return $this->currency;
    }

    /**
     * Get the current customer logged in. If no customer is logged return null
     *
     * @return \Thelia\Model\Customer|null
     */
    protected function getCustomer()
    {
        if (null === $this->customer) {
            $this->customer = $this->getSession() ? $this->getSession()->getCustomerUser() : null;
        }

        return $this->customer;
    }

    /**
     * Get the current lang used or if not present the default lang for the shop
     *
     * @return \Symfony\Component\Locale\Lang
     */
    protected function getLang()
    {
        if (null === $this->lang) {
            $this->lang = $this->getSession() ? $this->getSession()->getLang(true) : null;
        }
        if (null === $this->lang) {
            $this->lang = Lang::getDefaultLanguage();
        }

        return $this->lang;
    }


}
