<?php
/*************************************************************************************/
/*                                                                                   */
/*      Thelia	                                                                     */
/*                                                                                   */
/*      Copyright (c) OpenStudio                                                     */
/*	email : info@thelia.net                                                      */
/*      web : http://www.thelia.net                                                  */
/*                                                                                   */
/*      This program is free software; you can redistribute it and/or modify         */
/*      it under the terms of the GNU General Public License as published by         */
/*      the Free Software Foundation; either version 3 of the License                */
/*                                                                                   */
/*      This program is distributed in the hope that it will be useful,              */
/*      but WITHOUT ANY WARRANTY; without even the implied warranty of               */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                */
/*      GNU General Public License for more details.                                 */
/*                                                                                   */
/*      You should have received a copy of the GNU General Public License            */
/*	    along with this program. If not, see <http://www.gnu.org/licenses/>.     */
/*                                                                                   */
/*************************************************************************************/

namespace Thelia\Config\Dumper;


class TpexConfigDumper {

    protected $loops;
    protected $filters;
    protected $baseParams;
    protected $loopTests;

    public function __construct(array $loops, array $filters, array $baseParams, array $loopTests)
    {
        $this->loops = var_export($loops, true);
        $this->filters = var_export($filters, true);
        $this->baseParams = var_export($baseParams, true);
        $this->loopTests = var_export($loopTests, true);
    }

    public function dump()
    {

        $code = <<<EOF
<?php
/* File generated by \Thelia\Config\Dumper\TpexConfigDumper */
class TpexConfig
{

    public function getLoopConfig()
    {
        return {$this->loops};
    }

    public function getFilterConfig()
    {
        return {$this->filters};
    }

    public function getBaseParamConfig()
    {
        return {$this->baseParams};
    }

    public function getLoopTestConfig()
    {
        return {$this->loopTests};
    }
}
EOF;

    return $code;
    }


}