<?php
/**********************************************************************************/
/*                                                                                */
/*      Thelia	                                                                  */
/*                                                                                */
/*      Copyright (c) OpenStudio                                                  */
/*      email : info@thelia.net                                                   */
/*      web : http://www.thelia.net                                               */
/*                                                                                */
/*      This program is free software; you can redistribute it and/or modify      */
/*      it under the terms of the GNU General Public License as published by      */
/*      the Free Software Foundation; either version 3 of the License             */
/*                                                                                */
/*      This program is distributed in the hope that it will be useful,           */
/*      but WITHOUT ANY WARRANTY; without even the implied warranty of            */
/*      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             */
/*      GNU General Public License for more details.                              */
/*                                                                                */
/*      You should have received a copy of the GNU General Public License         */
/*	    along with this program. If not, see <http://www.gnu.org/licenses/>.      */
/*                                                                                */
/**********************************************************************************/

namespace Thelia\Coupon\Type;

use Thelia\Coupon\CouponAdapterInterface;
use Thelia\Coupon\Type\CouponAbstract;
use Thelia\Exception\MissingAdapterException;

/**
 * Created by JetBrains PhpStorm.
 * Date: 8/19/13
 * Time: 3:24 PM
 *
 * @package Coupon
 * @author  Guillaume MOREL <gmorel@openstudio.fr>
 *
 */
class RemoveXPercent extends CouponAbstract
{
    protected $percent = 0;

    /**
     * Constructor
     *
     * @param string $code              Coupon code (ex: XMAS)
     * @param string $title             Coupon title (ex: Coupon for XMAS)
     * @param string $shortDescription  Coupon short description
     * @param string $description       Coupon description
     * @param float  $percent           Coupon % to deduce (ex:3.14 for 3.14%)
     * @param bool   $isCumulative      if Coupon is cumulative
     * @param bool   $isRemovingPostage if Coupon is removing postage
     */
    function __construct($code, $title, $shortDescription, $description, $percent, $isCumulative, $isRemovingPostage)
    {
        $this->code = $code;
        $this->title = $title;
        $this->shortDescription = $shortDescription;
        $this->description = $description;

        $this->isCumulative = $isCumulative;
        $this->isRemovingPostage = $isRemovingPostage;

        $this->percent = $percent;
    }

    /**
     * Return effects generated by the coupon
     * A negative value
     *
     * @param CouponAdapterInterface $adapter allowing to gather
     *                               all necessary Thelia variables
     *
     * @throws \Thelia\Exception\MissingAdapterException
     * @throws \InvalidArgumentException
     * @return float
     */
    public function getDiscount(CouponAdapterInterface $adapter)
    {
        if ($this->percent >= 100) {
            throw new \InvalidArgumentException(
                'Percentage must be inferior to 100'
            );
        }

        $basePrice =$adapter
            ->getCartTotalPrice();

        return $basePrice * (( 100 - $this->percent ) / 100);
    }

}