<?php
/*************************************************************************************/
/*      This file is part of the Thelia package.                                     */
/*                                                                                   */
/*      Copyright (c) OpenStudio                                                     */
/*      email : dev@thelia.net                                                       */
/*      web : http://www.thelia.net                                                  */
/*                                                                                   */
/*      For the full copyright and license information, please view the LICENSE.txt  */
/*      file that was distributed with this source code.                             */
/*************************************************************************************/

namespace Thelia\Coupon\Type;

use Thelia\Coupon\FacadeInterface;

/**
 * @package Coupon
 * @author  Guillaume MOREL <gmorel@openstudio.fr>
 *
 */
class RemoveXPercent extends CouponAbstract
{
    const INPUT_PERCENTAGE_NAME = 'percentage';

    /** @var string Service Id  */
    protected $serviceId = 'thelia.coupon.type.remove_x_percent';

    /** @var float Percentage removed from the Cart */
    protected $percentage = 0;

    /** @var array Extended Inputs to manage */
    protected $extendedInputs = array(
        self::INPUT_PERCENTAGE_NAME
    );

    /**
     * @inheritdoc
     */
    public function set(
        FacadeInterface $facade,
        $code,
        $title,
        $shortDescription,
        $description,
        array $effects,
        $isCumulative,
        $isRemovingPostage,
        $isAvailableOnSpecialOffers,
        $isEnabled,
        $maxUsage,
        \DateTime $expirationDate,
        $freeShippingForCountries,
        $freeShippingForModules
    )
    {
        parent::set(
            $facade, $code, $title, $shortDescription, $description, $effects,
            $isCumulative, $isRemovingPostage, $isAvailableOnSpecialOffers, $isEnabled, $maxUsage, $expirationDate,
            $freeShippingForCountries,
            $freeShippingForModules
        );

        $this->percentage = $effects[self::INPUT_PERCENTAGE_NAME];

        return $this;
    }

    /**
     * Return effects generated by the coupon
     * A negative value
     *
     * @throws \Thelia\Exception\MissingFacadeException
     * @throws \InvalidArgumentException
     * @return float
     */
    public function exec()
    {
        if ($this->percentage >= 100) {
            throw new \InvalidArgumentException(
                'Percentage must be inferior to 100'
            );
        }

        return round($this->facade->getCartTotalTaxPrice() *  $this->percentage/100, 2);
    }

    /**
     * Get I18n name
     *
     * @return string
     */
    public function getName()
    {
        return $this->facade
            ->getTranslator()
            ->trans('Remove X percent to total cart', array(), 'coupon');
    }

    /**
     * Get I18n amount input name
     *
     * @return string
     */
    public function getInputName()
    {
        return $this->facade
            ->getTranslator()
            ->trans('Percent Discount', array(), 'coupon');
    }

    /**
     * Get I18n tooltip
     *
     * @return string
     */
    public function getToolTip()
    {
        $toolTip = $this->facade
            ->getTranslator()
            ->trans(
                'This coupon will offert a flat percentage off a shopper\'s entire order (not applied to shipping costs or tax rates). If the discount is greater than the total order corst, the customer will only pay the shipping, or nothing if the coupon also provides free shipping.',
                array(),
                'coupon'
            );

        return $toolTip;
    }

    /**
     * Draw the input displayed in the BackOffice
     * allowing Admin to set its Coupon effect
     *
     * @return string HTML string
     */
    public function drawBackOfficeInputs()
    {
        return $this->facade->getParser()->render('coupon/type-fragments/remove-x-percent.html', [
            'label'     => $this->getInputName(),
            'typeKey'   => self::INPUT_AMOUNT_NAME,
            'fieldId'   => self::INPUT_PERCENTAGE_NAME,
            'fieldName' => self::INPUT_EXTENDED__NAME,
            'value'     => $this->percentage
        ]);
    }
}
