<?php

/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio.
 */
namespace HookNavigation;

use Thelia\Module\BaseModule;

/**
 * Class HookNavigation.
 */
class HookNavigation extends BaseModule
{
    const MESSAGE_DOMAIN = 'hooknavigation';
    const ROUTER = 'router.hooknavigation';
}
