<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace HookNavigation;

use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;

/**
 * Class HookNavigation
 * @package HookNavigation
 */
class HookNavigation extends BaseModule
{
    const MESSAGE_DOMAIN = "hooknavigation";
    const ROUTER = "router.hooknavigation";

    public function postActivation(ConnectionInterface $con = null)
    {
    }
}
