INSERT INTO `lang`(`id`,`title`,`code`,`locale`,`url`,`date_format`,`time_format`,`datetime_format`,`decimal_separator`,`thousands_separator`,`decimals`,`by_default`,`created_at`,`updated_at`)VALUES
(1, 'Français', 'fr', 'fr_FR', '', 'd/m/Y', 'H:i:s', 'd/m/y H:i:s', ',', ' ', '2', '1', NOW(), NOW()),
(2, 'English', 'en', 'en_US', '', 'm-d-Y', 'h:i:s', 'm-d-Y h:i:s', '.', ' ', '2', '0', NOW(), NOW()),
(3, 'castellano', 'es', 'es_ES', '', 'm-d-Y', 'h:i:s', 'm-d-Y h:i:s', ',', '.', '2', '0', NOW(), NOW()),
(4, 'Italiano', 'it', 'it_IT', '', 'd/m/Y', 'H:i:s', 'd/m/y H:i:s', ',', ' ', '2', '0', NOW(), NOW());

INSERT INTO `config` (`name`, `value`, `secured`, `hidden`, `created_at`, `updated_at`) VALUES
('session_config.default', '1', 1, 1, NOW(), NOW()),
('verifyStock', '1', 0, 0, NOW(), NOW()),
('active-template', 'default', 0, 0, NOW(), NOW()),
('default_lang_without_translation', '1', 0, 0, NOW(), NOW()),
('rewriting_enable', '0', 0, 0, NOW(), NOW()),
('imagine_graphic_driver', 'gd', 0, 0, NOW(), NOW()),
('default_images_quality_percent', '75', 0, 0, NOW(), NOW()),
('original_image_delivery_mode', 'symlink', 0, 0, NOW(), NOW()),
('images_library_path', 'local/media/images', 0, 0, NOW(), NOW()),
('image_cache_dir_from_web_root', 'cache/images', 0, 0, NOW(), NOW()),
('currency_rate_update_url', 'http://www.ecb.int/stats/eurofxref/eurofxref-daily.xml', 0, 0, NOW(), NOW()),
('page_not_found_view', '404.html', 0, 0, NOW(), NOW()),
('use_tax_free_amounts', 0, 0, 0, NOW(), NOW()),
('process_assets', '1', 0, 0, NOW(), NOW()),
('thelia_admin_remember_me_cookie_name', 'tarmcn', 0, 0, NOW(), NOW()),
('thelia_admin_remember_me_cookie_expiration', 2592000, 0, 0, NOW(), NOW()),
('thelia_customer_remember_me_cookie_name', 'tcrmcn', 0, 0, NOW(), NOW()),
('thelia_customer_remember_me_cookie_expiration', 31536000, 0, 0, NOW(), NOW()),
('session_config.handlers', 'Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler', 0, 0, NOW(), NOW())
;


INSERT INTO `module` (`id`, `code`, `type`, `activate`, `position`, `full_namespace`, `created_at`, `updated_at`) VALUES
(1, 'DebugBar', 1, 1, 1, 'DebugBar\\DebugBar', NOW(), NOW());

INSERT INTO `customer_title`(`id`, `by_default`, `position`, `created_at`, `updated_at`) VALUES
(1, 1, 1, NOW(), NOW()),
(2, 0, 2, NOW(), NOW()),
(3, 0, 3, NOW(), NOW());

INSERT INTO `customer_title_i18n` (`id`, `locale`, `short`, `long`) VALUES
(1, 'fr_FR', 'Mr', 'Monsieur'),
(1, 'en_US', 'M', 'Mister'),
(2, 'fr_FR', 'Mme', 'Madame'),
(2, 'en_US', 'Mrs', 'Misses'),
(3, 'fr_FR', 'Mlle', 'Madamemoiselle'),
(3, 'en_US', 'Miss', 'Miss');

INSERT INTO `currency` (`id` ,`code` ,`symbol` ,`rate`, `position` ,`by_default` ,`created_at` ,`updated_at`)
VALUES
(1, 'EUR', '€', '1', 1, '1', NOW() , NOW()),
(2, 'USD', '$', '1.26', 2, '0', NOW(), NOW()),
(3, 'GBP', '£', '0.89', 3, '0', NOW(), NOW());

INSERT INTO `currency_i18n` (`id` ,`locale` ,`name`)
VALUES
(1, 'fr_FR', 'Euro'),
(1, 'en_US', 'Euro'),
(2, 'fr_FR', 'Dollar Américain'),
(2, 'en_US', 'United States Dollar'),
(3, 'fr_FR', 'Livre anglaise'),
(3, 'en_US', 'UK Pound');


INSERT INTO `country` (`id`, `area_id`, `isocode`, `isoalpha2`, `isoalpha3`, `created_at`, `updated_at`) VALUES
(1, NULL, '4', 'AF', 'AFG', NOW(), NOW()),
(2, NULL, '710', 'ZA', 'ZAF', NOW(), NOW()),
(3, NULL, '8', 'AL', 'ALB', NOW(), NOW()),
(4, NULL, '12', 'DZ', 'DZA', NOW(), NOW()),
(5, NULL, '276', 'DE', 'DEU', NOW(), NOW()),
(6, NULL, '20', 'AD', 'AND', NOW(), NOW()),
(7, NULL, '24', 'AO', 'AGO', NOW(), NOW()),
(8, NULL, '28', 'AG', 'ATG', NOW(), NOW()),
(9, NULL, '682', 'SA', 'SAU', NOW(), NOW()),
(10, NULL, '32', 'AR', 'ARG', NOW(), NOW()),
(11, NULL, '51', 'AM', 'ARM', NOW(), NOW()),
(12, NULL, '36', 'AU', 'AUS', NOW(), NOW()),
(13, NULL, '40', 'AT', 'AUT', NOW(), NOW()),
(14, NULL, '31', 'AZ', 'AZE', NOW(), NOW()),
(15, NULL, '44', 'BS', 'BHS', NOW(), NOW()),
(16, NULL, '48', 'BR', 'BHR', NOW(), NOW()),
(17, NULL, '50', 'BD', 'BGD', NOW(), NOW()),
(18, NULL, '52', 'BB', 'BRB', NOW(), NOW()),
(19, NULL, '585', 'PW', 'PLW', NOW(), NOW()),
(20, NULL, '56', 'BE', 'BEL', NOW(), NOW()),
(21, NULL, '84', 'BL', 'BLZ', NOW(), NOW()),
(22, NULL, '204', 'BJ', 'BEN', NOW(), NOW()),
(23, NULL, '64', 'BT', 'BTN', NOW(), NOW()),
(24, NULL, '112', 'BY', 'BLR', NOW(), NOW()),
(25, NULL, '104', 'MM', 'MMR', NOW(), NOW()),
(26, NULL, '68', 'BO', 'BOL', NOW(), NOW()),
(27, NULL, '70', 'BA', 'BIH', NOW(), NOW()),
(28, NULL, '72', 'BW', 'BWA', NOW(), NOW()),
(29, NULL, '76', 'BR', 'BRA', NOW(), NOW()),
(30, NULL, '96', 'BN', 'BRN', NOW(), NOW()),
(31, NULL, '100', 'BG', 'BGR', NOW(), NOW()),
(32, NULL, '854', 'BF', 'BFA', NOW(), NOW()),
(33, NULL, '108', 'BI', 'BDI', NOW(), NOW()),
(34, NULL, '116', 'KH', 'KHM', NOW(), NOW()),
(35, NULL, '120', 'CM', 'CMR', NOW(), NOW()),
(37, NULL, '132', 'CV', 'CPV', NOW(), NOW()),
(38, NULL, '152', 'CL', 'CHL', NOW(), NOW()),
(39, NULL, '156', 'CN', 'CHN', NOW(), NOW()),
(40, NULL, '196', 'CY', 'CYP', NOW(), NOW()),
(41, NULL, '170', 'CO', 'COL', NOW(), NOW()),
(42, NULL, '174', 'KM', 'COM', NOW(), NOW()),
(43, NULL, '178', 'CG', 'COG', NOW(), NOW()),
(44, NULL, '184', 'CK', 'COK', NOW(), NOW()),
(45, NULL, '408', 'KP', 'PRK', NOW(), NOW()),
(46, NULL, '410', 'KR', 'KOR', NOW(), NOW()),
(47, NULL, '188', 'CR', 'CRI', NOW(), NOW()),
(48, NULL, '384', 'CI', 'CIV', NOW(), NOW()),
(49, NULL, '191', 'HR', 'HRV', NOW(), NOW()),
(50, NULL, '192', 'CU', 'CUB', NOW(), NOW()),
(51, NULL, '208', 'DK', 'DNK', NOW(), NOW()),
(52, NULL, '262', 'DJ', 'DJI', NOW(), NOW()),
(53, NULL, '212', 'DM', 'DMA', NOW(), NOW()),
(54, NULL, '818', 'EG', 'EGY', NOW(), NOW()),
(55, NULL, '784', 'AE', 'ARE', NOW(), NOW()),
(56, NULL, '218', 'EC', 'ECU', NOW(), NOW()),
(57, NULL, '232', 'ER', 'ERI', NOW(), NOW()),
(58, NULL, '724', 'ES', 'ESP', NOW(), NOW()),
(59, NULL, '233', 'EE', 'EST', NOW(), NOW()),
(61, NULL, '231', 'ET', 'ETH', NOW(), NOW()),
(62, NULL, '242', 'FJ', 'FJI', NOW(), NOW()),
(63, NULL, '246', 'FI', 'FIN', NOW(), NOW()),
(64, NULL, '250', 'FR', 'FRA', NOW(), NOW()),
(65, NULL, '266', 'GA', 'GAB', NOW(), NOW()),
(66, NULL, '270', 'GM', 'GMB', NOW(), NOW()),
(67, NULL, '268', 'GE', 'GEO', NOW(), NOW()),
(68, NULL, '288', 'GH', 'GHA', NOW(), NOW()),
(69, NULL, '300', 'GR', 'GRC', NOW(), NOW()),
(70, NULL, '308', 'GD', 'GRD', NOW(), NOW()),
(71, NULL, '320', 'GT', 'GTM', NOW(), NOW()),
(72, NULL, '324', 'GN', 'GIN', NOW(), NOW()),
(73, NULL, '624', 'GW', 'GNB', NOW(), NOW()),
(74, NULL, '226', 'GQ', 'GNQ', NOW(), NOW()),
(75, NULL, '328', 'GY', 'GUY', NOW(), NOW()),
(76, NULL, '332', 'HT', 'HTI', NOW(), NOW()),
(77, NULL, '340', 'HN', 'HND', NOW(), NOW()),
(78, NULL, '348', 'HU', 'HUN', NOW(), NOW()),
(79, NULL, '356', 'IN', 'IND', NOW(), NOW()),
(80, NULL, '360', 'ID', 'IDN', NOW(), NOW()),
(81, NULL, '364', 'IR', 'IRN', NOW(), NOW()),
(82, NULL, '368', 'IQ', 'IRQ', NOW(), NOW()),
(83, NULL, '372', 'IE', 'IRL', NOW(), NOW()),
(84, NULL, '352', 'IS', 'ISL', NOW(), NOW()),
(85, NULL, '376', 'IL', 'ISR', NOW(), NOW()),
(86, NULL, '380', 'IT', 'ITA', NOW(), NOW()),
(87, NULL, '388', 'JM', 'JAM', NOW(), NOW()),
(88, NULL, '392', 'JP', 'JPN', NOW(), NOW()),
(89, NULL, '400', 'JO', 'JOR', NOW(), NOW()),
(90, NULL, '398', 'KZ', 'KAZ', NOW(), NOW()),
(91, NULL, '404', 'KE', 'KEN', NOW(), NOW()),
(92, NULL, '417', 'KG', 'KGZ', NOW(), NOW()),
(93, NULL, '296', 'KI', 'KIR', NOW(), NOW()),
(94, NULL, '414', 'KW', 'KWT', NOW(), NOW()),
(95, NULL, '418', 'LA', 'LAO', NOW(), NOW()),
(96, NULL, '426', 'LS', 'LSO', NOW(), NOW()),
(97, NULL, '428', 'LV', 'LVA', NOW(), NOW()),
(98, NULL, '422', 'LB', 'LBN', NOW(), NOW()),
(99, NULL, '430', 'LR', 'LBR', NOW(), NOW()),
(100, NULL, '343', 'LY', 'LBY', NOW(), NOW()),
(101, NULL, '438', 'LI', 'LIE', NOW(), NOW()),
(102, NULL, '440', 'LT', 'LTU', NOW(), NOW()),
(103, NULL, '442', 'LU', 'LUX', NOW(), NOW()),
(104, NULL, '807', 'MK', 'MKD', NOW(), NOW()),
(105, NULL, '450', 'MD', 'MDG', NOW(), NOW()),
(106, NULL, '458', 'MY', 'MYS', NOW(), NOW()),
(107, NULL, '454', 'MW', 'MWI', NOW(), NOW()),
(108, NULL, '462', 'MV', 'MDV', NOW(), NOW()),
(109, NULL, '466', 'ML', 'MLI', NOW(), NOW()),
(110, NULL, '470', 'MT', 'MLT', NOW(), NOW()),
(111, NULL, '504', 'MA', 'MAR', NOW(), NOW()),
(112, NULL, '584', 'MH', 'MHL', NOW(), NOW()),
(113, NULL, '480', 'MU', 'MUS', NOW(), NOW()),
(114, NULL, '478', 'MR', 'MRT', NOW(), NOW()),
(115, NULL, '484', 'MX', 'MEX', NOW(), NOW()),
(116, NULL, '583', 'FM', 'FSM', NOW(), NOW()),
(117, NULL, '498', 'MD', 'MDA', NOW(), NOW()),
(118, NULL, '492', 'MC', 'MCO', NOW(), NOW()),
(119, NULL, '496', 'MN', 'MNG', NOW(), NOW()),
(120, NULL, '508', 'MZ', 'MOZ', NOW(), NOW()),
(121, NULL, '516', 'NA', 'NAM', NOW(), NOW()),
(122, NULL, '520', 'NR', 'NRU', NOW(), NOW()),
(123, NULL, '524', 'NP', 'NPL', NOW(), NOW()),
(124, NULL, '558', 'NI', 'NIC', NOW(), NOW()),
(125, NULL, '562', 'NE', 'NER', NOW(), NOW()),
(126, NULL, '566', 'NG', 'NGA', NOW(), NOW()),
(127, NULL, '570', 'NU', 'NIU', NOW(), NOW()),
(128, NULL, '578', 'NO', 'NOR', NOW(), NOW()),
(129, NULL, '554', 'NZ', 'NZL', NOW(), NOW()),
(130, NULL, '512', 'OM', 'OMN', NOW(), NOW()),
(131, NULL, '800', 'UG', 'UGA', NOW(), NOW()),
(132, NULL, '860', 'UZ', 'UZB', NOW(), NOW()),
(133, NULL, '586', 'PK', 'PAK', NOW(), NOW()),
(134, NULL, '591', 'PA', 'PAN', NOW(), NOW()),
(135, NULL, '598', 'PG', 'PNG', NOW(), NOW()),
(136, NULL, '600', 'PY', 'PRY', NOW(), NOW()),
(137, NULL, '528', 'NL', 'NLD', NOW(), NOW()),
(138, NULL, '604', 'PE', 'PER', NOW(), NOW()),
(139, NULL, '608', 'PH', 'PHL', NOW(), NOW()),
(140, NULL, '616', 'PL', 'POL', NOW(), NOW()),
(141, NULL, '620', 'PT', 'PRT', NOW(), NOW()),
(142, NULL, '634', 'QA', 'QAT', NOW(), NOW()),
(143, NULL, '140', 'CF', 'CAF', NOW(), NOW()),
(144, NULL, '214', 'DO', 'DOM', NOW(), NOW()),
(145, NULL, '203', 'CZ', 'CZE', NOW(), NOW()),
(146, NULL, '642', 'RO', 'ROU', NOW(), NOW()),
(147, NULL, '826', 'GB', 'GBR', NOW(), NOW()),
(148, NULL, '643', 'RU', 'RUS', NOW(), NOW()),
(149, NULL, '646', 'RW', 'RWA', NOW(), NOW()),
(150, NULL, '659', 'KN', 'KNA', NOW(), NOW()),
(151, NULL, '662', 'LC', 'LCA', NOW(), NOW()),
(152, NULL, '674', 'SM', 'SMR', NOW(), NOW()),
(153, NULL, '670', 'VC', 'VCT', NOW(), NOW()),
(154, NULL, '90', 'SB', 'SLB', NOW(), NOW()),
(155, NULL, '222', 'SV', 'SLV', NOW(), NOW()),
(156, NULL, '882', 'WS', 'WSM', NOW(), NOW()),
(157, NULL, '678', 'ST', 'STP', NOW(), NOW()),
(158, NULL, '686', 'SN', 'SEN', NOW(), NOW()),
(159, NULL, '690', 'SC', 'SYC', NOW(), NOW()),
(160, NULL, '694', 'SL', 'SLE', NOW(), NOW()),
(161, NULL, '702', 'SG', 'SGP', NOW(), NOW()),
(162, NULL, '703', 'SK', 'SVK', NOW(), NOW()),
(163, NULL, '705', 'SI', 'SVN', NOW(), NOW()),
(164, NULL, '706', 'SO', 'SOM', NOW(), NOW()),
(165, NULL, '729', 'SD', 'SDN', NOW(), NOW()),
(166, NULL, '144', 'LK', 'LKA', NOW(), NOW()),
(167, NULL, '752', 'SE', 'SWE', NOW(), NOW()),
(168, NULL, '756', 'CH', 'CHE', NOW(), NOW()),
(169, NULL, '740', 'SR', 'SUR', NOW(), NOW()),
(170, NULL, '748', 'SZ', 'SWZ', NOW(), NOW()),
(171, NULL, '760', 'SY', 'SYR', NOW(), NOW()),
(172, NULL, '762', 'TJ', 'TJK', NOW(), NOW()),
(173, NULL, '834', 'TZ', 'TZA', NOW(), NOW()),
(174, NULL, '148', 'TD', 'TCD', NOW(), NOW()),
(175, NULL, '764', 'TH', 'THA', NOW(), NOW()),
(176, NULL, '768', 'TG', 'TGO', NOW(), NOW()),
(177, NULL, '776', 'TO', 'TON', NOW(), NOW()),
(178, NULL, '780', 'TT', 'TTO', NOW(), NOW()),
(179, NULL, '788', 'TN', 'TUN', NOW(), NOW()),
(180, NULL, '795', 'TM', 'TKM', NOW(), NOW()),
(181, NULL, '792', 'TR', 'TUR', NOW(), NOW()),
(182, NULL, '798', 'TV', 'TUV', NOW(), NOW()),
(183, NULL, '804', 'UA', 'UKR', NOW(), NOW()),
(184, NULL, '858', 'UY', 'URY', NOW(), NOW()),
(185, NULL, '336', 'VA', 'VAT', NOW(), NOW()),
(186, NULL, '548', 'VU', 'VUT', NOW(), NOW()),
(187, NULL, '862', 'VE', 'VEN', NOW(), NOW()),
(188, NULL, '704', 'VN', 'VNM', NOW(), NOW()),
(189, NULL, '887', 'YE', 'YEM', NOW(), NOW()),
(190, NULL, '807', 'MK', 'MKD', NOW(), NOW()),
(191, NULL, '180', 'CD', 'COD', NOW(), NOW()),
(192, NULL, '894', 'ZM', 'ZMB', NOW(), NOW()),
(193, NULL, '716', 'ZW', 'ZWE', NOW(), NOW()),
(196, NULL, '840', 'US', 'USA', NOW(), NOW()),
(197, NULL, '840', 'US', 'USA', NOW(), NOW()),
(198, NULL, '840', 'US', 'USA', NOW(), NOW()),
(199, NULL, '840', 'US', 'USA', NOW(), NOW()),
(200, NULL, '840', 'US', 'USA', NOW(), NOW()),
(201, NULL, '840', 'US', 'USA', NOW(), NOW()),
(202, NULL, '840', 'US', 'USA', NOW(), NOW()),
(203, NULL, '840', 'US', 'USA', NOW(), NOW()),
(204, NULL, '840', 'US', 'USA', NOW(), NOW()),
(205, NULL, '840', 'US', 'USA', NOW(), NOW()),
(206, NULL, '840', 'US', 'USA', NOW(), NOW()),
(207, NULL, '840', 'US', 'USA', NOW(), NOW()),
(208, NULL, '840', 'US', 'USA', NOW(), NOW()),
(209, NULL, '840', 'US', 'USA', NOW(), NOW()),
(210, NULL, '840', 'US', 'USA', NOW(), NOW()),
(211, NULL, '840', 'US', 'USA', NOW(), NOW()),
(212, NULL, '840', 'US', 'USA', NOW(), NOW()),
(213, NULL, '840', 'US', 'USA', NOW(), NOW()),
(214, NULL, '840', 'US', 'USA', NOW(), NOW()),
(215, NULL, '840', 'US', 'USA', NOW(), NOW()),
(216, NULL, '840', 'US', 'USA', NOW(), NOW()),
(217, NULL, '840', 'US', 'USA', NOW(), NOW()),
(218, NULL, '840', 'US', 'USA', NOW(), NOW()),
(219, NULL, '840', 'US', 'USA', NOW(), NOW()),
(220, NULL, '840', 'US', 'USA', NOW(), NOW()),
(221, NULL, '840', 'US', 'USA', NOW(), NOW()),
(222, NULL, '840', 'US', 'USA', NOW(), NOW()),
(223, NULL, '840', 'US', 'USA', NOW(), NOW()),
(224, NULL, '840', 'US', 'USA', NOW(), NOW()),
(225, NULL, '840', 'US', 'USA', NOW(), NOW()),
(226, NULL, '840', 'US', 'USA', NOW(), NOW()),
(227, NULL, '840', 'US', 'USA', NOW(), NOW()),
(228, NULL, '840', 'US', 'USA', NOW(), NOW()),
(229, NULL, '840', 'US', 'USA', NOW(), NOW()),
(230, NULL, '840', 'US', 'USA', NOW(), NOW()),
(231, NULL, '840', 'US', 'USA', NOW(), NOW()),
(232, NULL, '840', 'US', 'USA', NOW(), NOW()),
(233, NULL, '840', 'US', 'USA', NOW(), NOW()),
(234, NULL, '840', 'US', 'USA', NOW(), NOW()),
(235, NULL, '840', 'US', 'USA', NOW(), NOW()),
(236, NULL, '840', 'US', 'USA', NOW(), NOW()),
(237, NULL, '840', 'US', 'USA', NOW(), NOW()),
(238, NULL, '840', 'US', 'USA', NOW(), NOW()),
(239, NULL, '840', 'US', 'USA', NOW(), NOW()),
(240, NULL, '840', 'US', 'USA', NOW(), NOW()),
(241, NULL, '840', 'US', 'USA', NOW(), NOW()),
(242, NULL, '840', 'US', 'USA', NOW(), NOW()),
(243, NULL, '840', 'US', 'USA', NOW(), NOW()),
(244, NULL, '840', 'US', 'USA', NOW(), NOW()),
(245, NULL, '840', 'US', 'USA', NOW(), NOW()),
(246, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(247, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(248, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(249, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(250, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(251, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(252, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(253, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(254, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(255, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(256, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(257, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(258, NULL, '124', 'CA', 'CAN', NOW(), NOW()),
(259, NULL, '312', 'GP', 'GLP', NOW(), NOW()),
(260, NULL, '254', 'GF', 'GUF', NOW(), NOW()),
(261, NULL, '474', 'MQ', 'MTQ', NOW(), NOW()),
(262, NULL, '175', 'YT', 'MYT', NOW(), NOW()),
(263, NULL, '638', 'RE', 'REU', NOW(), NOW()),
(264, NULL, '666', 'PM', 'SPM', NOW(), NOW()),
(265, NULL, '540', 'NC', 'NCL', NOW(), NOW()),
(266, NULL, '258', 'PF', 'PYF', NOW(), NOW()),
(267, NULL, '876', 'WF', 'WLF', NOW(), NOW()),
(268, NULL, '840', 'US', 'USA', NOW(), NOW());

INSERT INTO `country_i18n` (`id`, `locale`, `title`, `description`, `chapo`, `postscriptum`) VALUES
(1, 'en_US', 'Afghanistan', '', '', ''),
(1, 'es_ES', 'Afganistán', '', '', ''),
(1, 'fr_FR', 'Afghanistan', '', '', ''),
(2, 'en_US', 'South Africa', '', '', ''),
(2, 'es_ES', 'Sudáfrica', '', '', ''),
(2, 'fr_FR', 'Afrique du Sud', '', '', ''),
(3, 'en_US', 'Albania', '', '', ''),
(3, 'es_ES', 'Albania', '', '', ''),
(3, 'fr_FR', 'Albanie', '', '', ''),
(4, 'en_US', 'Algeria', '', '', ''),
(4, 'es_ES', 'Argelia', '', '', ''),
(4, 'fr_FR', 'Algérie', '', '', ''),
(5, 'en_US', 'Germany', '', '', ''),
(5, 'es_ES', 'Alemania', '', '', ''),
(5, 'fr_FR', 'Allemagne', '', '', ''),
(6, 'en_US', 'Andorra', '', '', ''),
(6, 'es_ES', 'Andorra', '', '', ''),
(6, 'fr_FR', 'Andorre', '', '', ''),
(7, 'en_US', 'Angola', '', '', ''),
(7, 'es_ES', 'Angola', '', '', ''),
(7, 'fr_FR', 'Angola', '', '', ''),
(8, 'en_US', 'Antigua and Barbuda', '', '', ''),
(8, 'es_ES', 'Antigua y Barbuda', '', '', ''),
(8, 'fr_FR', 'Antigua-et-Barbuda', '', '', ''),
(9, 'en_US', 'Saudi Arabia', '', '', ''),
(9, 'es_ES', 'Arabia Saudita', '', '', ''),
(9, 'fr_FR', 'Arabie saoudite', '', '', ''),
(10, 'en_US', 'Argentina', '', '', ''),
(10, 'es_ES', 'Argentina', '', '', ''),
(10, 'fr_FR', 'Argentine', '', '', ''),
(11, 'en_US', 'Armenia', '', '', ''),
(11, 'es_ES', 'Armenia', '', '', ''),
(11, 'fr_FR', 'Arménie', '', '', ''),
(12, 'en_US', 'Australia', '', '', ''),
(12, 'es_ES', 'Australia', '', '', ''),
(12, 'fr_FR', 'Australie', '', '', ''),
(13, 'en_US', 'Austria', '', '', ''),
(13, 'es_ES', 'Austria', '', '', ''),
(13, 'fr_FR', 'Autriche', '', '', ''),
(14, 'en_US', 'Azerbaijan', '', '', ''),
(14, 'es_ES', 'Azerbaiyán', '', '', ''),
(14, 'fr_FR', 'Azerbaïdjan', '', '', ''),
(15, 'en_US', 'Bahamas', '', '', ''),
(15, 'es_ES', 'Bahamas', '', '', ''),
(15, 'fr_FR', 'Bahamas', '', '', ''),
(16, 'en_US', 'Bahrain', '', '', ''),
(16, 'es_ES', 'Bahrein', '', '', ''),
(16, 'fr_FR', 'Bahreïn', '', '', ''),
(17, 'en_US', 'Bangladesh', '', '', ''),
(17, 'es_ES', 'Bangladesh', '', '', ''),
(17, 'fr_FR', 'Bangladesh', '', '', ''),
(18, 'en_US', 'Barbados', '', '', ''),
(18, 'es_ES', 'Barbados', '', '', ''),
(18, 'fr_FR', 'Barbade', '', '', ''),
(19, 'en_US', 'Belarus', '', '', ''),
(19, 'es_ES', 'Belarús', '', '', ''),
(19, 'fr_FR', 'Belau', '', '', ''),
(20, 'en_US', 'Belgium', '', '', ''),
(20, 'es_ES', 'Bélgica', '', '', ''),
(20, 'fr_FR', 'Belgique', '', '', ''),
(21, 'en_US', 'Belize', '', '', ''),
(21, 'es_ES', 'Belice', '', '', ''),
(21, 'fr_FR', 'Belize', '', '', ''),
(22, 'en_US', 'Benin', '', '', ''),
(22, 'es_ES', 'Benin', '', '', ''),
(22, 'fr_FR', 'Bénin', '', '', ''),
(23, 'en_US', 'Bhutan', '', '', ''),
(23, 'es_ES', 'Bhután', '', '', ''),
(23, 'fr_FR', 'Bhoutan', '', '', ''),
(24, 'en_US', 'Bielorussia', '', '', ''),
(24, 'es_ES', 'Bielorusia', '', '', ''),
(24, 'fr_FR', 'Biélorussie', '', '', ''),
(25, 'en_US', 'Burma', '', '', ''),
(25, 'es_ES', 'Birmania', '', '', ''),
(25, 'fr_FR', 'Birmanie', '', '', ''),
(26, 'en_US', 'Bolivia', '', '', ''),
(26, 'es_ES', 'Bolivia', '', '', ''),
(26, 'fr_FR', 'Bolivie', '', '', ''),
(27, 'en_US', 'Bosnia and Herzegovina', '', '', ''),
(27, 'es_ES', 'Bosnia y Herzegovina', '', '', ''),
(27, 'fr_FR', 'Bosnie-Herzégovine', '', '', ''),
(28, 'en_US', 'Botswana', '', '', ''),
(28, 'es_ES', 'Botswana', '', '', ''),
(28, 'fr_FR', 'Botswana', '', '', ''),
(29, 'en_US', 'Brazil', '', '', ''),
(29, 'es_ES', 'Brasil', '', '', ''),
(29, 'fr_FR', 'Brésil', '', '', ''),
(30, 'en_US', 'Brunei', '', '', ''),
(30, 'es_ES', 'Brunei', '', '', ''),
(30, 'fr_FR', 'Brunei', '', '', ''),
(31, 'en_US', 'Bulgaria', '', '', ''),
(31, 'es_ES', 'Bulgaria', '', '', ''),
(31, 'fr_FR', 'Bulgarie', '', '', ''),
(32, 'en_US', 'Burkina', '', '', ''),
(32, 'es_ES', 'Burkina', '', '', ''),
(32, 'fr_FR', 'Burkina', '', '', ''),
(33, 'en_US', 'Burundi', '', '', ''),
(33, 'es_ES', 'Burundi', '', '', ''),
(33, 'fr_FR', 'Burundi', '', '', ''),
(34, 'en_US', 'Cambodia', '', '', ''),
(34, 'es_ES', 'Camboya', '', '', ''),
(34, 'fr_FR', 'Cambodge', '', '', ''),
(35, 'en_US', 'Cameroon', '', '', ''),
(35, 'es_ES', 'Camerún', '', '', ''),
(35, 'fr_FR', 'Cameroun', '', '', ''),
(37, 'en_US', 'Cape Verde', '', '', ''),
(37, 'es_ES', 'Cabo Verde', '', '', ''),
(37, 'fr_FR', 'Cap-Vert', '', '', ''),
(38, 'en_US', 'Chile', '', '', ''),
(38, 'es_ES', 'Chile', '', '', ''),
(38, 'fr_FR', 'Chili', '', '', ''),
(39, 'en_US', 'China', '', '', ''),
(39, 'es_ES', 'China', '', '', ''),
(39, 'fr_FR', 'Chine', '', '', ''),
(40, 'en_US', 'Cyprus', '', '', ''),
(40, 'es_ES', 'Chipre', '', '', ''),
(40, 'fr_FR', 'Chypre', '', '', ''),
(41, 'en_US', 'Colombia', '', '', ''),
(41, 'es_ES', 'Colombia', '', '', ''),
(41, 'fr_FR', 'Colombie', '', '', ''),
(42, 'en_US', 'Comoros', '', '', ''),
(42, 'es_ES', 'Comoras', '', '', ''),
(42, 'fr_FR', 'Comores', '', '', ''),
(43, 'en_US', 'Congo', '', '', ''),
(43, 'es_ES', 'Congo', '', '', ''),
(43, 'fr_FR', 'Congo', '', '', ''),
(44, 'en_US', 'Cook Islands', '', '', ''),
(44, 'es_ES', 'Cook', '', '', ''),
(44, 'fr_FR', 'Cook', '', '', ''),
(45, 'en_US', 'North Korea', '', '', ''),
(45, 'es_ES', 'Corea del Norte', '', '', ''),
(45, 'fr_FR', 'Corée du Nord', '', '', ''),
(46, 'en_US', 'South Korea', '', '', ''),
(46, 'es_ES', 'Corea del Sur', '', '', ''),
(46, 'fr_FR', 'Corée du Sud', '', '', ''),
(47, 'en_US', 'Costa Rica', '', '', ''),
(47, 'es_ES', 'Costa Rica', '', '', ''),
(47, 'fr_FR', 'Costa Rica', '', '', ''),
(48, 'en_US', 'Ivory Coast', '', '', ''),
(48, 'es_ES', 'Costa de Marfil', '', '', ''),
(48, 'fr_FR', 'Côte dIvoire', '', '', ''),
(49, 'en_US', 'Croatia', '', '', ''),
(49, 'es_ES', 'Croacia', '', '', ''),
(49, 'fr_FR', 'Croatie', '', '', ''),
(50, 'en_US', 'Cuba', '', '', ''),
(50, 'es_ES', 'Cuba', '', '', ''),
(50, 'fr_FR', 'Cuba', '', '', ''),
(51, 'en_US', 'Denmark', '', '', ''),
(51, 'es_ES', 'Dinamarca', '', '', ''),
(51, 'fr_FR', 'Danemark', '', '', ''),
(52, 'en_US', 'Djibouti', '', '', ''),
(52, 'es_ES', 'Djibouti', '', '', ''),
(52, 'fr_FR', 'Djibouti', '', '', ''),
(53, 'en_US', 'Dominica', '', '', ''),
(53, 'es_ES', 'Dominica', '', '', ''),
(53, 'fr_FR', 'Dominique', '', '', ''),
(54, 'en_US', 'Egypt', '', '', ''),
(54, 'es_ES', 'Egipto', '', '', ''),
(54, 'fr_FR', 'Égypte', '', '', ''),
(55, 'en_US', 'United Arab Emirates', '', '', ''),
(55, 'es_ES', 'Emiratos Árabes Unidos', '', '', ''),
(55, 'fr_FR', 'Émirats arabes unis', '', '', ''),
(56, 'en_US', 'Ecuador', '', '', ''),
(56, 'es_ES', 'Ecuador', '', '', ''),
(56, 'fr_FR', 'Équateur', '', '', ''),
(57, 'en_US', 'Eritrea', '', '', ''),
(57, 'es_ES', 'Eritrea', '', '', ''),
(57, 'fr_FR', 'Érythrée', '', '', ''),
(58, 'en_US', 'Spain', '', '', ''),
(58, 'es_ES', 'España', '', '', ''),
(58, 'fr_FR', 'Espagne', '', '', ''),
(59, 'en_US', 'Estonia', '', '', ''),
(59, 'es_ES', 'Estonia', '', '', ''),
(59, 'fr_FR', 'Estonie', '', '', ''),
(61, 'en_US', 'Ethiopia', '', '', ''),
(61, 'es_ES', 'Etiopía', '', '', ''),
(61, 'fr_FR', 'Éthiopie', '', '', ''),
(62, 'en_US', 'Fiji', '', '', ''),
(62, 'es_ES', 'Fiji', '', '', ''),
(62, 'fr_FR', 'Fidji', '', '', ''),
(63, 'en_US', 'Finland', '', '', ''),
(63, 'es_ES', 'Finlandia', '', '', ''),
(63, 'fr_FR', 'Finlande', '', '', ''),
(64, 'en_US', 'France metropolitan', '', '', ''),
(64, 'es_ES', 'Francia', '', '', ''),
(64, 'fr_FR', 'France métropolitaine', '', '', ''),
(65, 'en_US', 'Gabon', '', '', ''),
(65, 'es_ES', 'Gabón', '', '', ''),
(65, 'fr_FR', 'Gabon', '', '', ''),
(66, 'en_US', 'Gambia', '', '', ''),
(66, 'es_ES', 'Gambia', '', '', ''),
(66, 'fr_FR', 'Gambie', '', '', ''),
(67, 'en_US', 'Georgia', '', '', ''),
(67, 'es_ES', 'Georgia', '', '', ''),
(67, 'fr_FR', 'Géorgie', '', '', ''),
(68, 'en_US', 'Ghana', '', '', ''),
(68, 'es_ES', 'Ghana', '', '', ''),
(68, 'fr_FR', 'Ghana', '', '', ''),
(69, 'en_US', 'Greece', '', '', ''),
(69, 'es_ES', 'Grecia', '', '', ''),
(69, 'fr_FR', 'Grèce', '', '', ''),
(70, 'en_US', 'Grenada', '', '', ''),
(70, 'es_ES', 'Granada', '', '', ''),
(70, 'fr_FR', 'Grenade', '', '', ''),
(71, 'en_US', 'Guatemala', '', '', ''),
(71, 'es_ES', 'Guatemala', '', '', ''),
(71, 'fr_FR', 'Guatemala', '', '', ''),
(72, 'en_US', 'Guinea', '', '', ''),
(72, 'es_ES', 'Guinea', '', '', ''),
(72, 'fr_FR', 'Guinée', '', '', ''),
(73, 'en_US', 'Guinea-Bissau', '', '', ''),
(73, 'es_ES', 'Guinea-Bissau', '', '', ''),
(73, 'fr_FR', 'Guinée-Bissao', '', '', ''),
(74, 'en_US', 'Equatorial Guinea', '', '', ''),
(74, 'es_ES', 'Guinea Ecuatorial', '', '', ''),
(74, 'fr_FR', 'Guinée équatoriale', '', '', ''),
(75, 'en_US', 'Guyana', '', '', ''),
(75, 'es_ES', 'Guyana', '', '', ''),
(75, 'fr_FR', 'Guyana', '', '', ''),
(76, 'en_US', 'Haiti', '', '', ''),
(76, 'es_ES', 'Haití', '', '', ''),
(76, 'fr_FR', 'Haïti', '', '', ''),
(77, 'en_US', 'Honduras', '', '', ''),
(77, 'es_ES', 'Honduras', '', '', ''),
(77, 'fr_FR', 'Honduras', '', '', ''),
(78, 'en_US', 'Hungary', '', '', ''),
(78, 'es_ES', 'Hungría', '', '', ''),
(78, 'fr_FR', 'Hongrie', '', '', ''),
(79, 'en_US', 'India', '', '', ''),
(79, 'es_ES', 'India', '', '', ''),
(79, 'fr_FR', 'Inde', '', '', ''),
(80, 'en_US', 'Indonesia', '', '', ''),
(80, 'es_ES', 'Indonesia', '', '', ''),
(80, 'fr_FR', 'Indonésie', '', '', ''),
(81, 'en_US', 'Iran', '', '', ''),
(81, 'es_ES', 'Irán', '', '', ''),
(81, 'fr_FR', 'Iran', '', '', ''),
(82, 'en_US', 'Iraq', '', '', ''),
(82, 'es_ES', 'Iraq', '', '', ''),
(82, 'fr_FR', 'Iraq', '', '', ''),
(83, 'en_US', 'Ireland', '', '', ''),
(83, 'es_ES', 'Irlanda', '', '', ''),
(83, 'fr_FR', 'Irlande', '', '', ''),
(84, 'en_US', 'Iceland', '', '', ''),
(84, 'es_ES', 'Islandia', '', '', ''),
(84, 'fr_FR', 'Islande', '', '', ''),
(85, 'en_US', 'Israel', '', '', ''),
(85, 'es_ES', 'Israel', '', '', ''),
(85, 'fr_FR', 'Israël', '', '', ''),
(86, 'en_US', 'Italy', '', '', ''),
(86, 'es_ES', 'Italia', '', '', ''),
(86, 'fr_FR', 'Italie', '', '', ''),
(87, 'en_US', 'Jamaica', '', '', ''),
(87, 'es_ES', 'Jamaica', '', '', ''),
(87, 'fr_FR', 'Jamaïque', '', '', ''),
(88, 'en_US', 'Japan', '', '', ''),
(88, 'es_ES', 'Japón', '', '', ''),
(88, 'fr_FR', 'Japon', '', '', ''),
(89, 'en_US', 'Jordan', '', '', ''),
(89, 'es_ES', 'Jordania', '', '', ''),
(89, 'fr_FR', 'Jordanie', '', '', ''),
(90, 'en_US', 'Kazakhstan', '', '', ''),
(90, 'es_ES', 'Kazajstán', '', '', ''),
(90, 'fr_FR', 'Kazakhstan', '', '', ''),
(91, 'en_US', 'Kenya', '', '', ''),
(91, 'es_ES', 'Kenia', '', '', ''),
(91, 'fr_FR', 'Kenya', '', '', ''),
(92, 'en_US', 'Kyrgyzstan', '', '', ''),
(92, 'es_ES', 'Kirguistán', '', '', ''),
(92, 'fr_FR', 'Kirghizistan', '', '', ''),
(93, 'en_US', 'Kiribati', '', '', ''),
(93, 'es_ES', 'Kiribati', '', '', ''),
(93, 'fr_FR', 'Kiribati', '', '', ''),
(94, 'en_US', 'Kuwait', '', '', ''),
(94, 'es_ES', 'Kuwait', '', '', ''),
(94, 'fr_FR', 'Koweït', '', '', ''),
(95, 'en_US', 'Laos', '', '', ''),
(95, 'es_ES', 'Laos', '', '', ''),
(95, 'fr_FR', 'Laos', '', '', ''),
(96, 'en_US', 'Lesotho', '', '', ''),
(96, 'es_ES', 'Lesotho', '', '', ''),
(96, 'fr_FR', 'Lesotho', '', '', ''),
(97, 'en_US', 'Latvia', '', '', ''),
(97, 'es_ES', 'Letonia', '', '', ''),
(97, 'fr_FR', 'Lettonie', '', '', ''),
(98, 'en_US', 'Lebanon', '', '', ''),
(98, 'es_ES', 'Líbano', '', '', ''),
(98, 'fr_FR', 'Liban', '', '', ''),
(99, 'en_US', 'Liberia', '', '', ''),
(99, 'es_ES', 'Liberia', '', '', ''),
(99, 'fr_FR', 'Liberia', '', '', ''),
(100, 'en_US', 'Libya', '', '', ''),
(100, 'es_ES', 'Libia', '', '', ''),
(100, 'fr_FR', 'Libye', '', '', ''),
(101, 'en_US', 'Liechtenstein', '', '', ''),
(101, 'es_ES', 'Liechtenstein', '', '', ''),
(101, 'fr_FR', 'Liechtenstein', '', '', ''),
(102, 'en_US', 'Lithuania', '', '', ''),
(102, 'es_ES', 'Lituania', '', '', ''),
(102, 'fr_FR', 'Lituanie', '', '', ''),
(103, 'en_US', 'Luxembourg', '', '', ''),
(103, 'es_ES', 'Luxemburgo', '', '', ''),
(103, 'fr_FR', 'Luxembourg', '', '', ''),
(104, 'en_US', 'Macedonia', '', '', ''),
(104, 'es_ES', 'Macedonia', '', '', ''),
(104, 'fr_FR', 'Macédoine', '', '', ''),
(105, 'en_US', 'Madagascar', '', '', ''),
(105, 'es_ES', 'Madagascar', '', '', ''),
(105, 'fr_FR', 'Madagascar', '', '', ''),
(106, 'en_US', 'Malaysia', '', '', ''),
(106, 'es_ES', 'Malasia', '', '', ''),
(106, 'fr_FR', 'Malaisie', '', '', ''),
(107, 'en_US', 'Malawi', '', '', ''),
(107, 'es_ES', 'Malawi', '', '', ''),
(107, 'fr_FR', 'Malawi', '', '', ''),
(108, 'en_US', 'Maldives', '', '', ''),
(108, 'es_ES', 'Maldivas', '', '', ''),
(108, 'fr_FR', 'Maldives', '', '', ''),
(109, 'en_US', 'Mali', '', '', ''),
(109, 'es_ES', 'Malí', '', '', ''),
(109, 'fr_FR', 'Mali', '', '', ''),
(110, 'en_US', 'Malta', '', '', ''),
(110, 'es_ES', 'Malta', '', '', ''),
(110, 'fr_FR', 'Malte', '', '', ''),
(111, 'en_US', 'Morocco', '', '', ''),
(111, 'es_ES', 'Marruecos', '', '', ''),
(111, 'fr_FR', 'Maroc', '', '', ''),
(112, 'en_US', 'Marshall Islands', '', '', ''),
(112, 'es_ES', 'Marshall', '', '', ''),
(112, 'fr_FR', 'Marshall', '', '', ''),
(113, 'en_US', 'Mauritius', '', '', ''),
(113, 'es_ES', 'Mauricio', '', '', ''),
(113, 'fr_FR', 'Maurice', '', '', ''),
(114, 'en_US', 'Mauritania', '', '', ''),
(114, 'es_ES', 'Mauritania', '', '', ''),
(114, 'fr_FR', 'Mauritanie', '', '', ''),
(115, 'en_US', 'Mexico', '', '', ''),
(115, 'es_ES', 'Méjico', '', '', ''),
(115, 'fr_FR', 'Mexique', '', '', ''),
(116, 'en_US', 'Micronesia', '', '', ''),
(116, 'es_ES', 'Micronesia', '', '', ''),
(116, 'fr_FR', 'Micronésie', '', '', ''),
(117, 'en_US', 'Moldova', '', '', ''),
(117, 'es_ES', 'Moldova', '', '', ''),
(117, 'fr_FR', 'Moldavie', '', '', ''),
(118, 'en_US', 'Monaco', '', '', ''),
(118, 'es_ES', 'Mónaco', '', '', ''),
(118, 'fr_FR', 'Monaco', '', '', ''),
(119, 'en_US', 'Mongolia', '', '', ''),
(119, 'es_ES', 'Mongolia', '', '', ''),
(119, 'fr_FR', 'Mongolie', '', '', ''),
(120, 'en_US', 'Mozambique', '', '', ''),
(120, 'es_ES', 'Mozambique', '', '', ''),
(120, 'fr_FR', 'Mozambique', '', '', ''),
(121, 'en_US', 'Namibia', '', '', ''),
(121, 'es_ES', 'Namibia', '', '', ''),
(121, 'fr_FR', 'Namibie', '', '', ''),
(122, 'en_US', 'Nauru', '', '', ''),
(122, 'es_ES', 'Nauru', '', '', ''),
(122, 'fr_FR', 'Nauru', '', '', ''),
(123, 'en_US', 'Nepal', '', '', ''),
(123, 'es_ES', 'Nepal', '', '', ''),
(123, 'fr_FR', 'Népal', '', '', ''),
(124, 'en_US', 'Nicaragua', '', '', ''),
(124, 'es_ES', 'Nicaragua', '', '', ''),
(124, 'fr_FR', 'Nicaragua', '', '', ''),
(125, 'en_US', 'Niger', '', '', ''),
(125, 'es_ES', 'Níger', '', '', ''),
(125, 'fr_FR', 'Niger', '', '', ''),
(126, 'en_US', 'Nigeria', '', '', ''),
(126, 'es_ES', 'Nigeria', '', '', ''),
(126, 'fr_FR', 'Nigeria', '', '', ''),
(127, 'en_US', 'Niue', '', '', ''),
(127, 'es_ES', 'Niue', '', '', ''),
(127, 'fr_FR', 'Niue', '', '', ''),
(128, 'en_US', 'Norway', '', '', ''),
(128, 'es_ES', 'Noruega', '', '', ''),
(128, 'fr_FR', 'Norvège', '', '', ''),
(129, 'en_US', 'New Zealand', '', '', ''),
(129, 'es_ES', 'Nueva Zelandia', '', '', ''),
(129, 'fr_FR', 'Nouvelle-Zélande', '', '', ''),
(130, 'en_US', 'Oman', '', '', ''),
(130, 'es_ES', 'Omán', '', '', ''),
(130, 'fr_FR', 'Oman', '', '', ''),
(131, 'en_US', 'Uganda', '', '', ''),
(131, 'es_ES', 'Uganda', '', '', ''),
(131, 'fr_FR', 'Ouganda', '', '', ''),
(132, 'en_US', 'Uzbekistan', '', '', ''),
(132, 'es_ES', 'Uzbekistán', '', '', ''),
(132, 'fr_FR', 'Ouzbékistan', '', '', ''),
(133, 'en_US', 'Pakistan', '', '', ''),
(133, 'es_ES', 'Pakistán', '', '', ''),
(133, 'fr_FR', 'Pakistan', '', '', ''),
(134, 'en_US', 'Panama', '', '', ''),
(134, 'es_ES', 'Panamá', '', '', ''),
(134, 'fr_FR', 'Panama', '', '', ''),
(135, 'en_US', 'Papua Nueva Guinea', '', '', ''),
(135, 'es_ES', 'Papua Nueva Guinea', '', '', ''),
(135, 'fr_FR', 'Papouasie', '', '', ''),
(136, 'en_US', 'Paraguay', '', '', ''),
(136, 'es_ES', 'Paraguay', '', '', ''),
(136, 'fr_FR', 'Paraguay', '', '', ''),
(137, 'en_US', 'Netherlands', '', '', ''),
(137, 'es_ES', 'Países Bajos', '', '', ''),
(137, 'fr_FR', 'Pays-Bas', '', '', ''),
(138, 'en_US', 'Peru', '', '', ''),
(138, 'es_ES', 'Perú', '', '', ''),
(138, 'fr_FR', 'Pérou', '', '', ''),
(139, 'en_US', 'Philippines', '', '', ''),
(139, 'es_ES', 'Filipinas', '', '', ''),
(139, 'fr_FR', 'Philippines', '', '', ''),
(140, 'en_US', 'Poland', '', '', ''),
(140, 'es_ES', 'Polonia', '', '', ''),
(140, 'fr_FR', 'Pologne', '', '', ''),
(141, 'en_US', 'Portugal', '', '', ''),
(141, 'es_ES', 'Portugal', '', '', ''),
(141, 'fr_FR', 'Portugal', '', '', ''),
(142, 'en_US', 'Qatar', '', '', ''),
(142, 'es_ES', 'Qatar', '', '', ''),
(142, 'fr_FR', 'Qatar', '', '', ''),
(143, 'en_US', 'Central African Republic', '', '', ''),
(143, 'es_ES', 'República Centroafricana', '', '', ''),
(143, 'fr_FR', 'République centrafricaine', '', '', ''),
(144, 'en_US', 'Dominican Republic', '', '', ''),
(144, 'es_ES', 'República Dominicana', '', '', ''),
(144, 'fr_FR', 'République dominicaine', '', '', ''),
(145, 'en_US', 'Czech Republic', '', '', ''),
(145, 'es_ES', 'República Checa', '', '', ''),
(145, 'fr_FR', 'République tchèque', '', '', ''),
(146, 'en_US', 'Romania', '', '', ''),
(146, 'es_ES', 'Rumania', '', '', ''),
(146, 'fr_FR', 'Roumanie', '', '', ''),
(147, 'en_US', 'United Kingdom', '', '', ''),
(147, 'es_ES', 'Reino Unido', '', '', ''),
(147, 'fr_FR', 'Royaume-Uni', '', '', ''),
(148, 'en_US', 'Russia', '', '', ''),
(148, 'es_ES', 'Rusia', '', '', ''),
(148, 'fr_FR', 'Russie', '', '', ''),
(149, 'en_US', 'Rwanda', '', '', ''),
(149, 'es_ES', 'Ruanda', '', '', ''),
(149, 'fr_FR', 'Rwanda', '', '', ''),
(150, 'en_US', 'Saint Kitts and Nevis', '', '', ''),
(150, 'es_ES', 'San Cristóbal', '', '', ''),
(150, 'fr_FR', 'Saint-Christophe-et-Niévès', '', '', ''),
(151, 'en_US', 'Saint Lucia', '', '', ''),
(151, 'es_ES', 'Santa Lucía', '', '', ''),
(151, 'fr_FR', 'Sainte-Lucie', '', '', ''),
(152, 'en_US', 'San Marino', '', '', ''),
(152, 'es_ES', 'San Marino', '', '', ''),
(152, 'fr_FR', 'Saint-Marin', '', '', ''),
(153, 'en_US', 'Saint Vincent and the Grenadines', '', '', ''),
(153, 'es_ES', 'San Vicente y las Granadinas', '', '', ''),
(153, 'fr_FR', 'Saint-Vincent-et-les Grenadines', '', '', ''),
(154, 'en_US', 'Solomon Islands', '', '', ''),
(154, 'es_ES', 'Salomón', '', '', ''),
(154, 'fr_FR', 'Salomon', '', '', ''),
(155, 'en_US', 'El Salvador', '', '', ''),
(155, 'es_ES', 'El Salvador', '', '', ''),
(155, 'fr_FR', 'Salvador', '', '', ''),
(156, 'en_US', 'Western Samoa', '', '', ''),
(156, 'es_ES', 'Samoa', '', '', ''),
(156, 'fr_FR', 'Samoa occidentales', '', '', ''),
(157, 'en_US', 'Sao Tome and Principe', '', '', ''),
(157, 'es_ES', 'Santo Tomé y Príncipe', '', '', ''),
(157, 'fr_FR', 'Sao Tomé-et-Principe', '', '', ''),
(158, 'en_US', 'Senegal', '', '', ''),
(158, 'es_ES', 'Senegal', '', '', ''),
(158, 'fr_FR', 'Sénégal', '', '', ''),
(159, 'en_US', 'Seychelles', '', '', ''),
(159, 'es_ES', 'Seychelles', '', '', ''),
(159, 'fr_FR', 'Seychelles', '', '', ''),
(160, 'en_US', 'Sierra Leone', '', '', ''),
(160, 'es_ES', 'Sierra Leona', '', '', ''),
(160, 'fr_FR', 'Sierra Leone', '', '', ''),
(161, 'en_US', 'Singapore', '', '', ''),
(161, 'es_ES', 'Singapur', '', '', ''),
(161, 'fr_FR', 'Singapour', '', '', ''),
(162, 'en_US', 'Slovakia', '', '', ''),
(162, 'es_ES', 'Eslovaquia', '', '', ''),
(162, 'fr_FR', 'Slovaquie', '', '', ''),
(163, 'en_US', 'Slovenia', '', '', ''),
(163, 'es_ES', 'Eslovenia', '', '', ''),
(163, 'fr_FR', 'Slovénie', '', '', ''),
(164, 'en_US', 'Somalia', '', '', ''),
(164, 'es_ES', 'Somalia', '', '', ''),
(164, 'fr_FR', 'Somalie', '', '', ''),
(165, 'en_US', 'Sudan', '', '', ''),
(165, 'es_ES', 'Sudán', '', '', ''),
(165, 'fr_FR', 'Soudan', '', '', ''),
(166, 'en_US', 'Sri Lanka', '', '', ''),
(166, 'es_ES', 'Sri Lanka', '', '', ''),
(166, 'fr_FR', 'Sri Lanka', '', '', ''),
(167, 'en_US', 'Sweden', '', '', ''),
(167, 'es_ES', 'Suecia', '', '', ''),
(167, 'fr_FR', 'Suède', '', '', ''),
(168, 'en_US', 'Switzerland', '', '', ''),
(168, 'es_ES', 'Suiza', '', '', ''),
(168, 'fr_FR', 'Suisse', '', '', ''),
(169, 'en_US', 'Suriname', '', '', ''),
(169, 'es_ES', 'Suriname', '', '', ''),
(169, 'fr_FR', 'Suriname', '', '', ''),
(170, 'en_US', 'Swaziland', '', '', ''),
(170, 'es_ES', 'Swazilandia', '', '', ''),
(170, 'fr_FR', 'Swaziland', '', '', ''),
(171, 'en_US', 'Syria', '', '', ''),
(171, 'es_ES', 'Siria', '', '', ''),
(171, 'fr_FR', 'Syrie', '', '', ''),
(172, 'en_US', 'Tajikistan', '', '', ''),
(172, 'es_ES', 'Tayikistán', '', '', ''),
(172, 'fr_FR', 'Tadjikistan', '', '', ''),
(173, 'en_US', 'Tanzania', '', '', ''),
(173, 'es_ES', 'Tanzanía', '', '', ''),
(173, 'fr_FR', 'Tanzanie', '', '', ''),
(174, 'en_US', 'Chad', '', '', ''),
(174, 'es_ES', 'Chad', '', '', ''),
(174, 'fr_FR', 'Tchad', '', '', ''),
(175, 'en_US', 'Thailand', '', '', ''),
(175, 'es_ES', 'Tailandia', '', '', ''),
(175, 'fr_FR', 'Thaïlande', '', '', ''),
(176, 'en_US', 'Togo', '', '', ''),
(176, 'es_ES', 'Togo', '', '', ''),
(176, 'fr_FR', 'Togo', '', '', ''),
(177, 'en_US', 'Tonga', '', '', ''),
(177, 'es_ES', 'Tonga', '', '', ''),
(177, 'fr_FR', 'Tonga', '', '', ''),
(178, 'en_US', 'Trinidad and Tobago', '', '', ''),
(178, 'es_ES', 'Trinidad y Tabago', '', '', ''),
(178, 'fr_FR', 'Trinité-et-Tobago', '', '', ''),
(179, 'en_US', 'Tunisia', '', '', ''),
(179, 'es_ES', 'Túnez', '', '', ''),
(179, 'fr_FR', 'Tunisie', '', '', ''),
(180, 'en_US', 'Turkmenistan', '', '', ''),
(180, 'es_ES', 'Turkmenistán', '', '', ''),
(180, 'fr_FR', 'Turkménistan', '', '', ''),
(181, 'en_US', 'Turkey', '', '', ''),
(181, 'es_ES', 'Turquía', '', '', ''),
(181, 'fr_FR', 'Turquie', '', '', ''),
(182, 'en_US', 'Tuvalu', '', '', ''),
(182, 'es_ES', 'Tuvalu', '', '', ''),
(182, 'fr_FR', 'Tuvalu', '', '', ''),
(183, 'en_US', 'Ukraine', '', '', ''),
(183, 'es_ES', 'Ucrania', '', '', ''),
(183, 'fr_FR', 'Ukraine', '', '', ''),
(184, 'en_US', 'Uruguay', '', '', ''),
(184, 'es_ES', 'Uruguay', '', '', ''),
(184, 'fr_FR', 'Uruguay', '', '', ''),
(185, 'en_US', 'The Vatican', '', '', ''),
(185, 'es_ES', 'El Vatican', '', '', ''),
(185, 'fr_FR', 'Vatican', '', '', ''),
(186, 'en_US', 'Vanuatu', '', '', ''),
(186, 'es_ES', 'Vanuatu', '', '', ''),
(186, 'fr_FR', 'Vanuatu', '', '', ''),
(187, 'en_US', 'Venezuela', '', '', ''),
(187, 'es_ES', 'Venezuela', '', '', ''),
(187, 'fr_FR', 'Venezuela', '', '', ''),
(188, 'en_US', 'Vietnam', '', '', ''),
(188, 'es_ES', 'Viet Nam', '', '', ''),
(188, 'fr_FR', 'Viêt Nam', '', '', ''),
(189, 'en_US', 'Yemen', '', '', ''),
(189, 'es_ES', 'Yemen', '', '', ''),
(189, 'fr_FR', 'Yémen', '', '', ''),
(190, 'en_US', 'Yougoslavia', '', '', ''),
(190, 'es_ES', 'Yugoslavia', '', '', ''),
(190, 'fr_FR', 'Yougoslavie', '', '', ''),
(191, 'en_US', 'Zaire', '', '', ''),
(191, 'es_ES', 'Zaire', '', '', ''),
(191, 'fr_FR', 'Zaïre', '', '', ''),
(192, 'en_US', 'Zambia', '', '', ''),
(192, 'es_ES', 'Zambia', '', '', ''),
(192, 'fr_FR', 'Zambie', '', '', ''),
(193, 'en_US', 'Zimbabwe', '', '', ''),
(193, 'es_ES', 'Zimbabwe', '', '', ''),
(193, 'fr_FR', 'Zimbabwe', '', '', ''),
(196, 'en_US', 'USA - Alaska', '', '', ''),
(196, 'es_ES', 'USA - Alaska', '', '', ''),
(196, 'fr_FR', 'USA - Alaska', '', '', ''),
(197, 'en_US', 'USA - Arizona', '', '', ''),
(197, 'es_ES', 'USA - Arizona', '', '', ''),
(197, 'fr_FR', 'USA - Arizona', '', '', ''),
(198, 'en_US', 'USA - Arkansas', '', '', ''),
(198, 'es_ES', 'USA - Arkansas', '', '', ''),
(198, 'fr_FR', 'USA - Arkansas', '', '', ''),
(199, 'en_US', 'USA - California', '', '', ''),
(199, 'es_ES', 'USA - California', '', '', ''),
(199, 'fr_FR', 'USA - California', '', '', ''),
(200, 'en_US', 'USA - Colorado', '', '', ''),
(200, 'es_ES', 'USA - Colorado', '', '', ''),
(200, 'fr_FR', 'USA - Colorado', '', '', ''),
(201, 'en_US', 'USA - Connecticut', '', '', ''),
(201, 'es_ES', 'USA - Connecticut', '', '', ''),
(201, 'fr_FR', 'USA - Connecticut', '', '', ''),
(202, 'en_US', 'USA - Delaware', '', '', ''),
(202, 'es_ES', 'USA - Delaware', '', '', ''),
(202, 'fr_FR', 'USA - Delaware', '', '', ''),
(203, 'en_US', 'USA - District Of Columbia', '', '', ''),
(203, 'es_ES', 'USA - District Of Columbia', '', '', ''),
(203, 'fr_FR', 'USA - District Of Columbia', '', '', ''),
(204, 'en_US', 'USA - Florida', '', '', ''),
(204, 'es_ES', 'USA - Florida', '', '', ''),
(204, 'fr_FR', 'USA - Florida', '', '', ''),
(205, 'en_US', 'USA - Georgia', '', '', ''),
(205, 'es_ES', 'USA - Georgia', '', '', ''),
(205, 'fr_FR', 'USA - Georgia', '', '', ''),
(206, 'en_US', 'USA - Hawaii', '', '', ''),
(206, 'es_ES', 'USA - Hawaii', '', '', ''),
(206, 'fr_FR', 'USA - Hawaii', '', '', ''),
(207, 'en_US', 'USA - Idaho', '', '', ''),
(207, 'es_ES', 'USA - Idaho', '', '', ''),
(207, 'fr_FR', 'USA - Idaho', '', '', ''),
(208, 'en_US', 'USA - Illinois', '', '', ''),
(208, 'es_ES', 'USA - Illinois', '', '', ''),
(208, 'fr_FR', 'USA - Illinois', '', '', ''),
(209, 'en_US', 'USA - Indiana', '', '', ''),
(209, 'es_ES', 'USA - Indiana', '', '', ''),
(209, 'fr_FR', 'USA - Indiana', '', '', ''),
(210, 'en_US', 'USA - Iowa', '', '', ''),
(210, 'es_ES', 'USA - Iowa', '', '', ''),
(210, 'fr_FR', 'USA - Iowa', '', '', ''),
(211, 'en_US', 'USA - Kansas', '', '', ''),
(211, 'es_ES', 'USA - Kansas', '', '', ''),
(211, 'fr_FR', 'USA - Kansas', '', '', ''),
(212, 'en_US', 'USA - Kentucky', '', '', ''),
(212, 'es_ES', 'USA - Kentucky', '', '', ''),
(212, 'fr_FR', 'USA - Kentucky', '', '', ''),
(213, 'en_US', 'USA - Louisiana', '', '', ''),
(213, 'es_ES', 'USA - Louisiana', '', '', ''),
(213, 'fr_FR', 'USA - Louisiana', '', '', ''),
(214, 'en_US', 'USA - Maine', '', '', ''),
(214, 'es_ES', 'USA - Maine', '', '', ''),
(214, 'fr_FR', 'USA - Maine', '', '', ''),
(215, 'en_US', 'USA - Maryland', '', '', ''),
(215, 'es_ES', 'USA - Maryland', '', '', ''),
(215, 'fr_FR', 'USA - Maryland', '', '', ''),
(216, 'en_US', 'USA - Massachusetts', '', '', ''),
(216, 'es_ES', 'USA - Massachusetts', '', '', ''),
(216, 'fr_FR', 'USA - Massachusetts', '', '', ''),
(217, 'en_US', 'USA - Michigan', '', '', ''),
(217, 'es_ES', 'USA - Michigan', '', '', ''),
(217, 'fr_FR', 'USA - Michigan', '', '', ''),
(218, 'en_US', 'USA - Minnesota', '', '', ''),
(218, 'es_ES', 'USA - Minnesota', '', '', ''),
(218, 'fr_FR', 'USA - Minnesota', '', '', ''),
(219, 'en_US', 'USA - Mississippi', '', '', ''),
(219, 'es_ES', 'USA - Mississippi', '', '', ''),
(219, 'fr_FR', 'USA - Mississippi', '', '', ''),
(220, 'en_US', 'USA - Missouri', '', '', ''),
(220, 'es_ES', 'USA - Missouri', '', '', ''),
(220, 'fr_FR', 'USA - Missouri', '', '', ''),
(221, 'en_US', 'USA - Montana', '', '', ''),
(221, 'es_ES', 'USA - Montana', '', '', ''),
(221, 'fr_FR', 'USA - Montana', '', '', ''),
(222, 'en_US', 'USA - Nebraska', '', '', ''),
(222, 'es_ES', 'USA - Nebraska', '', '', ''),
(222, 'fr_FR', 'USA - Nebraska', '', '', ''),
(223, 'en_US', 'USA - Nevada', '', '', ''),
(223, 'es_ES', 'USA - Nevada', '', '', ''),
(223, 'fr_FR', 'USA - Nevada', '', '', ''),
(224, 'en_US', 'USA - New Hampshire', '', '', ''),
(224, 'es_ES', 'USA - New Hampshire', '', '', ''),
(224, 'fr_FR', 'USA - New Hampshire', '', '', ''),
(225, 'en_US', 'USA - New Jersey', '', '', ''),
(225, 'es_ES', 'USA - New Jersey', '', '', ''),
(225, 'fr_FR', 'USA - New Jersey', '', '', ''),
(226, 'en_US', 'USA - New Mexico', '', '', ''),
(226, 'es_ES', 'USA - New Mexico', '', '', ''),
(226, 'fr_FR', 'USA - New Mexico', '', '', ''),
(227, 'en_US', 'USA - New York', '', '', ''),
(227, 'es_ES', 'USA - New York', '', '', ''),
(227, 'fr_FR', 'USA - New York', '', '', ''),
(228, 'en_US', 'USA - North Carolina', '', '', ''),
(228, 'es_ES', 'USA - North Carolina', '', '', ''),
(228, 'fr_FR', 'USA - North Carolina', '', '', ''),
(229, 'en_US', 'USA - North Dakota', '', '', ''),
(229, 'es_ES', 'USA - North Dakota', '', '', ''),
(229, 'fr_FR', 'USA - North Dakota', '', '', ''),
(230, 'en_US', 'USA - Ohio', '', '', ''),
(230, 'es_ES', 'USA - Ohio', '', '', ''),
(230, 'fr_FR', 'USA - Ohio', '', '', ''),
(231, 'en_US', 'USA - Oklahoma', '', '', ''),
(231, 'es_ES', 'USA - Oklahoma', '', '', ''),
(231, 'fr_FR', 'USA - Oklahoma', '', '', ''),
(232, 'en_US', 'USA - Oregon', '', '', ''),
(232, 'es_ES', 'USA - Oregon', '', '', ''),
(232, 'fr_FR', 'USA - Oregon', '', '', ''),
(233, 'en_US', 'USA - Pennsylvania', '', '', ''),
(233, 'es_ES', 'USA - Pennsylvania', '', '', ''),
(233, 'fr_FR', 'USA - Pennsylvania', '', '', ''),
(234, 'en_US', 'USA - Rhode Island', '', '', ''),
(234, 'es_ES', 'USA - Rhode Island', '', '', ''),
(234, 'fr_FR', 'USA - Rhode Island', '', '', ''),
(235, 'en_US', 'USA - South Carolina', '', '', ''),
(235, 'es_ES', 'USA - South Carolina', '', '', ''),
(235, 'fr_FR', 'USA - South Carolina', '', '', ''),
(236, 'en_US', 'USA - South Dakota', '', '', ''),
(236, 'es_ES', 'USA - South Dakota', '', '', ''),
(236, 'fr_FR', 'USA - South Dakota', '', '', ''),
(237, 'en_US', 'USA - Tennessee', '', '', ''),
(237, 'es_ES', 'USA - Tennessee', '', '', ''),
(237, 'fr_FR', 'USA - Tennessee', '', '', ''),
(238, 'en_US', 'USA - Texas', '', '', ''),
(238, 'es_ES', 'USA - Texas', '', '', ''),
(238, 'fr_FR', 'USA - Texas', '', '', ''),
(239, 'en_US', 'USA - Utah', '', '', ''),
(239, 'es_ES', 'USA - Utah', '', '', ''),
(239, 'fr_FR', 'USA - Utah', '', '', ''),
(240, 'en_US', 'USA - Vermont', '', '', ''),
(240, 'es_ES', 'USA - Vermont', '', '', ''),
(240, 'fr_FR', 'USA - Vermont', '', '', ''),
(241, 'en_US', 'USA - Virginia', '', '', ''),
(241, 'es_ES', 'USA - Virginia', '', '', ''),
(241, 'fr_FR', 'USA - Virginia', '', '', ''),
(242, 'en_US', 'USA - Washington', '', '', ''),
(242, 'es_ES', 'USA - Washington', '', '', ''),
(242, 'fr_FR', 'USA - Washington', '', '', ''),
(243, 'en_US', 'USA - West Virginia', '', '', ''),
(243, 'es_ES', 'USA - West Virginia', '', '', ''),
(243, 'fr_FR', 'USA - West Virginia', '', '', ''),
(244, 'en_US', 'USA - Wisconsin', '', '', ''),
(244, 'es_ES', 'USA - Wisconsin', '', '', ''),
(244, 'fr_FR', 'USA - Wisconsin', '', '', ''),
(245, 'en_US', 'USA - Wyoming', '', '', ''),
(245, 'es_ES', 'USA - Wyoming', '', '', ''),
(245, 'fr_FR', 'USA - Wyoming', '', '', ''),
(246, 'en_US', 'Canada - Colombie-Britannique', '', '', ''),
(246, 'es_ES', 'Canada - Colombie-Britannique', '', '', ''),
(246, 'fr_FR', 'Canada - Colombie-Britannique', '', '', ''),
(247, 'en_US', 'Canada - Alberta', '', '', ''),
(247, 'es_ES', 'Canada - Alberta', '', '', ''),
(247, 'fr_FR', 'Canada - Alberta', '', '', ''),
(248, 'en_US', 'Canada - Saskatchewan', '', '', ''),
(248, 'es_ES', 'Canada - Saskatchewan', '', '', ''),
(248, 'fr_FR', 'Canada - Saskatchewan', '', '', ''),
(249, 'en_US', 'Canada - Manitoba', '', '', ''),
(249, 'es_ES', 'Canada - Manitoba', '', '', ''),
(249, 'fr_FR', 'Canada - Manitoba', '', '', ''),
(250, 'en_US', 'Canada - Ontario', '', '', ''),
(250, 'es_ES', 'Canada - Ontario', '', '', ''),
(250, 'fr_FR', 'Canada - Ontario', '', '', ''),
(251, 'en_US', 'Canada - Québec', '', '', ''),
(251, 'es_ES', 'Canada - Québec', '', '', ''),
(251, 'fr_FR', 'Canada - Québec', '', '', ''),
(252, 'en_US', 'Canada - Nouveau-Brunswick', '', '', ''),
(252, 'es_ES', 'Canada - Nouveau-Brunswick', '', '', ''),
(252, 'fr_FR', 'Canada - Nouveau-Brunswick', '', '', ''),
(253, 'en_US', 'Canada - Nouvelle-Écosse', '', '', ''),
(253, 'es_ES', 'Canada - Nouvelle-Écosse', '', '', ''),
(253, 'fr_FR', 'Canada - Nouvelle-Écosse', '', '', ''),
(254, 'en_US', 'Canada - Île-du-Prince-Édouard    ', '', '', ''),
(254, 'es_ES', 'Canada - Île-du-Prince-Édouard    ', '', '', ''),
(254, 'fr_FR', 'Canada - Île-du-Prince-Édouard    ', '', '', ''),
(255, 'en_US', 'Canada - Terre-Neuve-et-Labrador    ', '', '', ''),
(255, 'es_ES', 'Canada - Terre-Neuve-et-Labrador    ', '', '', ''),
(255, 'fr_FR', 'Canada - Terre-Neuve-et-Labrador    ', '', '', ''),
(256, 'en_US', 'Canada - Yukon', '', '', ''),
(256, 'es_ES', 'Canada - Yukon', '', '', ''),
(256, 'fr_FR', 'Canada - Yukon', '', '', ''),
(257, 'en_US', 'Canada - Territoires-du-Nord-Ouest', '', '', ''),
(257, 'es_ES', 'Canada - Territoires-du-Nord-Ouest', '', '', ''),
(257, 'fr_FR', 'Canada - Territoires-du-Nord-Ouest', '', '', ''),
(258, 'en_US', 'Canada - Nunavut', '', '', ''),
(258, 'es_ES', 'Canada - Nunavut', '', '', ''),
(258, 'fr_FR', 'Canada - Nunavut', '', '', ''),
(259, 'en_US', 'Guadeloupe', '', '', ''),
(259, 'es_ES', 'Guadeloupe', '', '', ''),
(259, 'fr_FR', 'Guadeloupe', '', '', ''),
(260, 'en_US', 'Guyane Française', '', '', ''),
(260, 'es_ES', 'Guyane Française', '', '', ''),
(260, 'fr_FR', 'Guyane Française', '', '', ''),
(261, 'en_US', 'Martinique', '', '', ''),
(261, 'es_ES', 'Martinique', '', '', ''),
(261, 'fr_FR', 'Martinique', '', '', ''),
(262, 'en_US', 'Mayotte', '', '', ''),
(262, 'es_ES', 'Mayotte', '', '', ''),
(262, 'fr_FR', 'Mayotte', '', '', ''),
(263, 'en_US', 'Réunion(La)', '', '', ''),
(263, 'es_ES', 'Réunion(La)', '', '', ''),
(263, 'fr_FR', 'Réunion(La)', '', '', ''),
(264, 'en_US', 'St Pierre et Miquelon', '', '', ''),
(264, 'es_ES', 'St Pierre et Miquelon', '', '', ''),
(264, 'fr_FR', 'St Pierre et Miquelon', '', '', ''),
(265, 'en_US', 'Nouvelle-Calédonie', '', '', ''),
(265, 'es_ES', 'Nouvelle-Calédonie', '', '', ''),
(265, 'fr_FR', 'Nouvelle-Calédonie', '', '', ''),
(266, 'en_US', 'Polynésie française', '', '', ''),
(266, 'es_ES', 'Polynésie française', '', '', ''),
(266, 'fr_FR', 'Polynésie française', '', '', ''),
(267, 'en_US', 'Wallis-et-Futuna', '', '', ''),
(267, 'es_ES', 'Wallis-et-Futuna', '', '', ''),
(267, 'fr_FR', 'Wallis-et-Futuna', '', '', ''),
(268, 'en_US', 'USA - Alabama', '', '', ''),
(268, 'es_ES', 'USA - Alabama', '', '', ''),
(268, 'fr_FR', 'USA - Alabama', '', '', '');

INSERT INTO  `tax` (`id`, `type`, `serialized_requirements`, `created_at`, `updated_at`)
  VALUES
  (1, 'PricePercentTaxType', 'eyJwZXJjZW50IjoxOS42fQ==', NOW(), NOW());

INSERT INTO `tax_i18n` (`id`, `locale`, `title`)
  VALUES
  (1, 'fr_FR', 'TVA française à 19.6%'),
  (1, 'en_UK', 'french 19.6% tax');

INSERT INTO  `tax_rule` (`id`, `created_at`, `updated_at`)
  VALUES
  (1, NOW(), NOW());

INSERT INTO `tax_rule_i18n` (`id`, `locale`, `title`)
  VALUES
  (1, 'fr_FR', 'TVA française à 19.6%'),
  (1, 'en_UK', 'french 19.6% tax');

INSERT INTO  `tax_rule_country` (`tax_rule_id`, `country_id`, `tax_id`, `position`, `created_at`, `updated_at`)
  VALUES
  (1, 64, 1, 1, NOW(), NOW());
