SET FOREIGN_KEY_CHECKS = 0;

UPDATE `config` SET `value`='2.2.0-alpha1' WHERE `name`='thelia_version';
UPDATE `config` SET `value`='2' WHERE `name`='thelia_major_version';
UPDATE `config` SET `value`='2' WHERE `name`='thelia_minus_version';
UPDATE `config` SET `value`='0' WHERE `name`='thelia_release_version';
UPDATE `config` SET `value`='alpha1' WHERE `name`='thelia_extra_version';

-- order status

SELECT @max_id := MAX(`id`) FROM `order_status`;

INSERT INTO `order_status` VALUES
  (@max_id + 1, "refunded", NOW(), NOW())
;

INSERT INTO `order_status_i18n` VALUES
(@max_id + 1, "ar_SA", NULL, "", "", ""),
(@max_id + 1, "de_DE", 'Zrückerstattet', "", "", ""),
(@max_id + 1, "en_US", 'Refunded', "", "", ""),
(@max_id + 1, "es_ES", NULL, "", "", ""),
(@max_id + 1, "fr_FR", 'Remboursé', "", "", ""),
(@max_id + 1, "it_IT", NULL, "", "", ""),
(@max_id + 1, "pt_BR", NULL, "", "", ""),
(@max_id + 1, "tr_TR", 'Geri ödeme', "", "", "")
;

-- new column in admin_log

ALTER TABLE `admin_log` ADD `resource_id` INTEGER AFTER `resource` ;

-- new config

SELECT @max_id := IFNULL(MAX(`id`),0) FROM `config`;

INSERT INTO `config` (`id`, `name`, `value`, `secured`, `hidden`, `created_at`, `updated_at`) VALUES
(@max_id + 1, 'customer_change_email', '0', 0, 0, NOW(), NOW()),
(@max_id + 2, 'customer_confirm_email', '0', 0, 0, NOW(), NOW())
;

INSERT INTO `config_i18n` (`id`, `locale`, `title`, `description`, `chapo`, `postscriptum`) VALUES
(@max_id + 1, 'ar_SA', NULL, NULL, NULL, NULL),
(@max_id + 2, 'ar_SA', NULL, NULL, NULL, NULL),
(@max_id + 1, 'de_DE', 'Den Kunden erlauben ihre E-Mail-Adresse zu ändern. 1 für Ja, 0 für Nein', NULL, NULL, NULL),
(@max_id + 2, 'de_DE', 'Den Kunden fragen, ihre E-Mail-Adresse zu bestätigen. 1 für Jan, 0 für Nein', NULL, NULL, NULL),
(@max_id + 1, 'en_US', 'Allow customers to change their email. 1 for yes, 0 for no', NULL, NULL, NULL),
(@max_id + 2, 'en_US', 'Ask the customers to confirm their email, 1 for yes, 0 for no', NULL, NULL, NULL),
(@max_id + 1, 'es_ES', NULL, NULL, NULL, NULL),
(@max_id + 2, 'es_ES', NULL, NULL, NULL, NULL),
(@max_id + 1, 'fr_FR', 'Permettre aux utilisateurs de changer leur email. 1 pour oui, 0 pour non', NULL, NULL, NULL),
(@max_id + 2, 'fr_FR', 'Demander aux clients de confirmer leur email. 1 pour oui, 0 pour non', NULL, NULL, NULL),
(@max_id + 1, 'it_IT', NULL, NULL, NULL, NULL),
(@max_id + 2, 'it_IT', NULL, NULL, NULL, NULL),
(@max_id + 1, 'pt_BR', NULL, NULL, NULL, NULL),
(@max_id + 2, 'pt_BR', NULL, NULL, NULL, NULL),
(@max_id + 1, 'tr_TR', 'Müşterilerin kendi e-posta değiştirmek izin. Evet için 1, hayır için 0', NULL, NULL, NULL),
(@max_id + 2, 'tr_TR', 'Onların 1 e-posta, \"Evet,\" için onaylamak için müşteriler sormak 0 hayır için', NULL, NULL, NULL)
;

-- country area table

create table IF NOT EXISTS `country_area`
(
    `country_id` INTEGER NOT NULL,
    `area_id` INTEGER NOT NULL,
    `created_at` DATETIME,
    `updated_at` DATETIME,
    INDEX `country_area_area_id_idx` (`area_id`),
    INDEX `fk_country_area_country_id_idx` (`country_id`),
    CONSTRAINT `fk_country_area_area_id`
        FOREIGN KEY (`area_id`)
        REFERENCES `area` (`id`)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT `fk_country_area_country_id`
        FOREIGN KEY (`country_id`)
        REFERENCES `country` (`id`)
        ON UPDATE RESTRICT
        ON DELETE CASCADE
) ENGINE=InnoDB CHARACTER SET='utf8';

-- Initialize the table with existing data
INSERT INTO `country_area` (`country_id`, `area_id`, `created_at`, `updated_at`) select `id`, `area_id`, NOW(), NOW() FROM `country` WHERE `area_id` IS NOT NULL;

-- Remove area_id column from country table
ALTER TABLE `country` DROP FOREIGN KEY `fk_country_area_id`;
ALTER TABLE `country` DROP KEY `idx_country_area_id`;
ALTER TABLE `country` DROP COLUMN `area_id`;
ALTER TABLE `category` ADD COLUMN `default_template_id` INTEGER AFTER  `position`;

-- new hook --
SELECT @max_id := IFNULL(MAX(`id`),0) FROM `hook`;

INSERT INTO `hook` (`id`, `code`, `type`, `by_module`, `block`, `native`, `activate`, `position`, `created_at`, `updated_at`) VALUES
(@max_id + 1, 'profile.table-header', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 2, 'profile.table-row', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 3, 'import.table-header', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 4, 'import.table-row', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 5, 'export.table-header', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 6, 'export.table-row', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 7, 'category-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 8, 'category-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 9, 'brand-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 10, 'brand-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 11, 'attribute-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 12, 'attribute-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 13, 'currency-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 14, 'currency-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 15, 'country-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 16, 'country-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 17, 'content-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 18, 'content-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 19, 'feature-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 20, 'feature-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 21, 'document-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 22, 'document-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 23, 'customer-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 24, 'customer-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 25, 'image-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 26, 'image-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 27, 'hook-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 28, 'hook-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 29, 'folder-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 30, 'folder-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 31, 'module-hook-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 32, 'module-hook-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 33, 'module-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 34, 'module-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 35, 'message-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 36, 'message-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 37, 'profile-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 38, 'profile-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 39, 'product-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 40, 'product-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 41, 'order-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 42, 'order-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 43, 'shipping-zones-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 44, 'shipping-zones-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 45, 'shipping-configuration-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 46, 'shipping-configuration-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 47, 'sale-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 48, 'sale-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 49, 'variables-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 50, 'variables-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 51, 'template-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 52, 'template-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 53, 'tax-rule-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 54, 'tax-rule-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 55, 'tax-edit.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 56, 'tax-edit.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 57, 'order-edit.product-list', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 58, 'order.tab', 2, 0, 1, 1, 1, 1, NOW(), NOW()),
(@max_id + 59, 'account-order.product', 1, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 60, 'tab-seo.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 61, 'tab-seo.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 62, 'tab-image.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 63, 'tab-image.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 64, 'tab-document.top', 2, 0, 0, 1, 1, 1, NOW(), NOW()),
(@max_id + 65, 'tab-document.bottom', 2, 0, 0, 1, 1, 1, NOW(), NOW())
;

INSERT INTO  `hook_i18n` (`id`, `locale`, `title`, `description`, `chapo`) VALUES
(@max_id + 1, 'ar_SA', NULL, '', ''),
(@max_id + 2, 'ar_SA', NULL, '', ''),
(@max_id + 3, 'ar_SA', NULL, '', ''),
(@max_id + 4, 'ar_SA', NULL, '', ''),
(@max_id + 5, 'ar_SA', NULL, '', ''),
(@max_id + 6, 'ar_SA', NULL, '', ''),
(@max_id + 7, 'ar_SA', NULL, '', ''),
(@max_id + 8, 'ar_SA', NULL, '', ''),
(@max_id + 9, 'ar_SA', NULL, '', ''),
(@max_id + 10, 'ar_SA', NULL, '', ''),
(@max_id + 11, 'ar_SA', NULL, '', ''),
(@max_id + 12, 'ar_SA', NULL, '', ''),
(@max_id + 13, 'ar_SA', NULL, '', ''),
(@max_id + 14, 'ar_SA', NULL, '', ''),
(@max_id + 15, 'ar_SA', NULL, '', ''),
(@max_id + 16, 'ar_SA', NULL, '', ''),
(@max_id + 17, 'ar_SA', NULL, '', ''),
(@max_id + 18, 'ar_SA', NULL, '', ''),
(@max_id + 19, 'ar_SA', NULL, '', ''),
(@max_id + 20, 'ar_SA', NULL, '', ''),
(@max_id + 21, 'ar_SA', NULL, '', ''),
(@max_id + 22, 'ar_SA', NULL, '', ''),
(@max_id + 23, 'ar_SA', NULL, '', ''),
(@max_id + 24, 'ar_SA', NULL, '', ''),
(@max_id + 25, 'ar_SA', NULL, '', ''),
(@max_id + 26, 'ar_SA', NULL, '', ''),
(@max_id + 27, 'ar_SA', NULL, '', ''),
(@max_id + 28, 'ar_SA', NULL, '', ''),
(@max_id + 29, 'ar_SA', NULL, '', ''),
(@max_id + 30, 'ar_SA', NULL, '', ''),
(@max_id + 31, 'ar_SA', NULL, '', ''),
(@max_id + 32, 'ar_SA', NULL, '', ''),
(@max_id + 33, 'ar_SA', NULL, '', ''),
(@max_id + 34, 'ar_SA', NULL, '', ''),
(@max_id + 35, 'ar_SA', NULL, '', ''),
(@max_id + 36, 'ar_SA', NULL, '', ''),
(@max_id + 37, 'ar_SA', NULL, '', ''),
(@max_id + 38, 'ar_SA', NULL, '', ''),
(@max_id + 39, 'ar_SA', NULL, '', ''),
(@max_id + 40, 'ar_SA', NULL, '', ''),
(@max_id + 41, 'ar_SA', NULL, '', ''),
(@max_id + 42, 'ar_SA', NULL, '', ''),
(@max_id + 43, 'ar_SA', NULL, '', ''),
(@max_id + 44, 'ar_SA', NULL, '', ''),
(@max_id + 45, 'ar_SA', NULL, '', ''),
(@max_id + 46, 'ar_SA', NULL, '', ''),
(@max_id + 47, 'ar_SA', NULL, '', ''),
(@max_id + 48, 'ar_SA', NULL, '', ''),
(@max_id + 49, 'ar_SA', NULL, '', ''),
(@max_id + 50, 'ar_SA', NULL, '', ''),
(@max_id + 51, 'ar_SA', NULL, '', ''),
(@max_id + 52, 'ar_SA', NULL, '', ''),
(@max_id + 53, 'ar_SA', NULL, '', ''),
(@max_id + 54, 'ar_SA', NULL, '', ''),
(@max_id + 55, 'ar_SA', NULL, '', ''),
(@max_id + 56, 'ar_SA', NULL, '', ''),
(@max_id + 57, 'ar_SA', NULL, '', ''),
(@max_id + 58, 'ar_SA', NULL, '', ''),
(@max_id + 59, 'ar_SA', NULL, '', ''),
(@max_id + 60, 'ar_SA', NULL, '', ''),
(@max_id + 61, 'ar_SA', NULL, '', ''),
(@max_id + 62, 'ar_SA', NULL, '', ''),
(@max_id + 63, 'ar_SA', NULL, '', ''),
(@max_id + 64, 'ar_SA', NULL, '', ''),
(@max_id + 65, 'ar_SA', NULL, '', ''),
(@max_id + 1, 'de_DE', 'Profil - Tabellenkopf', '', ''),
(@max_id + 2, 'de_DE', 'Profil - Tabellenzeile', '', ''),
(@max_id + 3, 'de_DE', 'Import - Tabellenkopf', '', ''),
(@max_id + 4, 'de_DE', 'Import - Tabellenzeile', '', ''),
(@max_id + 5, 'de_DE', 'Export - Tabellenkopf', '', ''),
(@max_id + 6, 'de_DE', 'Export - Tabellenzeile', '', ''),
(@max_id + 7, 'de_DE', 'Kategorie Bearbeitung - oben', '', ''),
(@max_id + 8, 'de_DE', 'Kategorie Bearbeitung - unten', '', ''),
(@max_id + 9, 'de_DE', 'Marke Bearbeitung - oben', '', ''),
(@max_id + 10, 'de_DE', 'Marke Bearbeitung - unten', '', ''),
(@max_id + 11, 'de_DE', 'Deklination Bearbeitung - oben', '', ''),
(@max_id + 12, 'de_DE', 'Deklination Bearbeitung - unten', '', ''),
(@max_id + 13, 'de_DE', 'Währung Bearbeitung - oben', '', ''),
(@max_id + 14, 'de_DE', 'Währung Bearbeitung - unten', '', ''),
(@max_id + 15, 'de_DE', 'Währung Bearbeitung - oben', '', ''),
(@max_id + 16, 'de_DE', 'Währung Bearbeitung - unten', '', ''),
(@max_id + 17, 'de_DE', 'Inhalt Bearbeitung - oben', '', ''),
(@max_id + 18, 'de_DE', 'Inhalt Bearbeitung - unten', '', ''),
(@max_id + 19, 'de_DE', 'Charakteristik Bearbeitung - oben', '', ''),
(@max_id + 20, 'de_DE', 'Charakteristik Bearbeitung - unten', '', ''),
(@max_id + 21, 'de_DE', 'Dokument Bearbeitung - oben', '', ''),
(@max_id + 22, 'de_DE', 'Dokument Bearbeitung - unten', '', ''),
(@max_id + 23, 'de_DE', 'Kunde Bearbeitung - oben', '', ''),
(@max_id + 24, 'de_DE', 'Kunde Bearbeitung - unten', '', ''),
(@max_id + 25, 'de_DE', 'Bild Bearbeitung - oben', '', ''),
(@max_id + 26, 'de_DE', 'Bild Bearbeitung - unten', '', ''),
(@max_id + 27, 'de_DE', 'Hook Bearbeitung - oben', '', ''),
(@max_id + 28, 'de_DE', 'Hook Bearbeitung - unten', '', ''),
(@max_id + 29, 'de_DE', 'Ordner Bearbeitung - oben', '', ''),
(@max_id + 30, 'de_DE', 'Ordner Bearbeitung - unten', '', ''),
(@max_id + 31, 'de_DE', 'Modul-Hook Bearbeitung - oben', '', ''),
(@max_id + 32, 'de_DE', 'Modul-Hook Bearbeitung - unten', '', ''),
(@max_id + 33, 'de_DE', 'Modul Bearbeitung - oben', '', ''),
(@max_id + 34, 'de_DE', 'Modul Bearbeitung - unten', '', ''),
(@max_id + 35, 'de_DE', 'Nachricht Bearbeitung - oben', '', ''),
(@max_id + 36, 'de_DE', 'Nachricht Bearbeitung - unten', '', ''),
(@max_id + 37, 'de_DE', 'Profil Bearbeitung - oben', '', ''),
(@max_id + 38, 'de_DE', 'Profil Bearbeitung - unten', '', ''),
(@max_id + 39, 'de_DE', 'Produkt Bearbeitung - oben', '', ''),
(@max_id + 40, 'de_DE', 'Produkt Bearbeitung - unten', '', ''),
(@max_id + 41, 'de_DE', 'Bestellung Bearbeitung - oben', '', ''),
(@max_id + 42, 'de_DE', 'Bestellung Bearbeitung - unten', '', ''),
(@max_id + 43, 'de_DE', 'Transporteur Lieferzonen Bearbeitung - oben', '', ''),
(@max_id + 44, 'de_DE', 'Transporteur Lieferzonen Bearbeitung - unten', '', ''),
(@max_id + 45, 'de_DE', 'Lieferzone Bearbeitung - oben', '', ''),
(@max_id + 46, 'de_DE', 'Lieferzone Bearbeitung - unten', '', ''),
(@max_id + 47, 'de_DE', 'Sonderangebot Bearbeitung - oben', '', ''),
(@max_id + 48, 'de_DE', 'Sonderangebot Bearbeitung - unten', '', ''),
(@max_id + 49, 'de_DE', 'Variable Bearbeitung - oben', '', ''),
(@max_id + 50, 'de_DE', 'Variable Bearbeitung - unten', '', ''),
(@max_id + 51, 'de_DE', 'Template Bearbeitung - oben', '', ''),
(@max_id + 52, 'de_DE', 'Template Bearbeitung - unten', '', ''),
(@max_id + 53, 'de_DE', 'Taxregel Bearbeitung - oben', '', ''),
(@max_id + 54, 'de_DE', 'Taxregel Bearbeitung - unten', '', ''),
(@max_id + 55, 'de_DE', 'Taxe Bearbeitung - oben', '', ''),
(@max_id + 56, 'de_DE', 'Taxe Bearbeitung - unten', '', ''),
(@max_id + 57, 'de_DE', 'Bestellungs Bearbeitung - unter die Produktdaten', '', ''),
(@max_id + 58, 'de_DE', 'Bestellung - Tab', '', ''),
(@max_id + 59, 'de_DE', 'Bestelldaten - nach einem Produkt', '', ''),
(@max_id + 60, 'de_DE', 'SEO Tab - oben', '', ''),
(@max_id + 61, 'de_DE', 'SEO Tab - unten', '', ''),
(@max_id + 62, 'de_DE', 'Bild Tab - oben', '', ''),
(@max_id + 63, 'de_DE', 'Bild Tab - unten', '', ''),
(@max_id + 64, 'de_DE', 'Dokument Tab - oben', '', ''),
(@max_id + 65, 'de_DE', 'Dokument Tab - unten', '', ''),
(@max_id + 1, 'en_US', 'Profile - table header', '', ''),
(@max_id + 2, 'en_US', 'Profile - table row', '', ''),
(@max_id + 3, 'en_US', 'Import - table header', '', ''),
(@max_id + 4, 'en_US', 'Import - table row', '', ''),
(@max_id + 5, 'en_US', 'Export - table header', '', ''),
(@max_id + 6, 'en_US', 'Export - table row', '', ''),
(@max_id + 7, 'en_US', 'Category edit - top', '', ''),
(@max_id + 8, 'en_US', 'Category edit - bottom', '', ''),
(@max_id + 9, 'en_US', 'Brand edit - top', '', ''),
(@max_id + 10, 'en_US', 'Brand edit - bottom', '', ''),
(@max_id + 11, 'en_US', 'Attribute edit - top', '', ''),
(@max_id + 12, 'en_US', 'Attribute edit - bottom', '', ''),
(@max_id + 13, 'en_US', 'Currency edit - top', '', ''),
(@max_id + 14, 'en_US', 'Currency edit - bottom', '', ''),
(@max_id + 15, 'en_US', 'Country edit - top', '', ''),
(@max_id + 16, 'en_US', 'Country edit - bottom', '', ''),
(@max_id + 17, 'en_US', 'Content edit - top', '', ''),
(@max_id + 18, 'en_US', 'Content edit - bottom', '', ''),
(@max_id + 19, 'en_US', 'Feature edit - top', '', ''),
(@max_id + 20, 'en_US', 'Feature edit - bottom', '', ''),
(@max_id + 21, 'en_US', 'Document edit - top', '', ''),
(@max_id + 22, 'en_US', 'Document edit - bottom', '', ''),
(@max_id + 23, 'en_US', 'Client edit - top', '', ''),
(@max_id + 24, 'en_US', 'Client edit - bottom', '', ''),
(@max_id + 25, 'en_US', 'Image edit - top', '', ''),
(@max_id + 26, 'en_US', 'Image edit - bottom', '', ''),
(@max_id + 27, 'en_US', 'Hook edit - top', '', ''),
(@max_id + 28, 'en_US', 'Hook edit - bottom', '', ''),
(@max_id + 29, 'en_US', 'Folder edit - top', '', ''),
(@max_id + 30, 'en_US', 'Folder edit - bottom', '', ''),
(@max_id + 31, 'en_US', 'Module hook edit - top', '', ''),
(@max_id + 32, 'en_US', 'Module hook edit - bottom', '', ''),
(@max_id + 33, 'en_US', 'Module edit - top', '', ''),
(@max_id + 34, 'en_US', 'Module edit - bottom', '', ''),
(@max_id + 35, 'en_US', 'Message edit - top', '', ''),
(@max_id + 36, 'en_US', 'Message edit - bottom', '', ''),
(@max_id + 37, 'en_US', 'Profile edit - top', '', ''),
(@max_id + 38, 'en_US', 'Profile edit - bottom', '', ''),
(@max_id + 39, 'en_US', 'Product edit - top', '', ''),
(@max_id + 40, 'en_US', 'Product edit - bottom', '', ''),
(@max_id + 41, 'en_US', 'Order edit - top', '', ''),
(@max_id + 42, 'en_US', 'Order edit - bottom', '', ''),
(@max_id + 43, 'en_US', 'Shipping zones edit - top', '', ''),
(@max_id + 44, 'en_US', 'Shipping zones edit - bottom', '', ''),
(@max_id + 45, 'en_US', 'Shipping configuration edit - top', '', ''),
(@max_id + 46, 'en_US', 'Shipping configuration edit - bottom', '', ''),
(@max_id + 47, 'en_US', 'Sale edit - top', '', ''),
(@max_id + 48, 'en_US', 'Sale edit - bottom', '', ''),
(@max_id + 49, 'en_US', 'Variable edit - top', '', ''),
(@max_id + 50, 'en_US', 'Variable edit - bottom', '', ''),
(@max_id + 51, 'en_US', 'Template edit - top', '', ''),
(@max_id + 52, 'en_US', 'Template edit - bottom', '', ''),
(@max_id + 53, 'en_US', 'Tax rule edit - top', '', ''),
(@max_id + 54, 'en_US', 'Tax rule edit - bottom', '', ''),
(@max_id + 55, 'en_US', 'Tax edit - top', '', ''),
(@max_id + 56, 'en_US', 'Tax edit - bottom', '', ''),
(@max_id + 57, 'en_US', 'Order edit - displayed after product information', '', ''),
(@max_id + 58, 'en_US', 'Order - Tab', '', ''),
(@max_id + 59, 'en_US', 'Order details - after product', '', ''),
(@max_id + 60, 'en_US', 'Tab SEO - top', '', ''),
(@max_id + 61, 'en_US', 'Tab SEO - bottom', '', ''),
(@max_id + 62, 'en_US', 'Tab image - top', '', ''),
(@max_id + 63, 'en_US', 'Tab image - bottom', '', ''),
(@max_id + 64, 'en_US', 'Tab document - top', '', ''),
(@max_id + 65, 'en_US', 'Tab document - bottom', '', ''),
(@max_id + 1, 'es_ES', NULL, '', ''),
(@max_id + 2, 'es_ES', NULL, '', ''),
(@max_id + 3, 'es_ES', NULL, '', ''),
(@max_id + 4, 'es_ES', NULL, '', ''),
(@max_id + 5, 'es_ES', NULL, '', ''),
(@max_id + 6, 'es_ES', NULL, '', ''),
(@max_id + 7, 'es_ES', NULL, '', ''),
(@max_id + 8, 'es_ES', NULL, '', ''),
(@max_id + 9, 'es_ES', NULL, '', ''),
(@max_id + 10, 'es_ES', NULL, '', ''),
(@max_id + 11, 'es_ES', NULL, '', ''),
(@max_id + 12, 'es_ES', NULL, '', ''),
(@max_id + 13, 'es_ES', NULL, '', ''),
(@max_id + 14, 'es_ES', NULL, '', ''),
(@max_id + 15, 'es_ES', NULL, '', ''),
(@max_id + 16, 'es_ES', NULL, '', ''),
(@max_id + 17, 'es_ES', NULL, '', ''),
(@max_id + 18, 'es_ES', NULL, '', ''),
(@max_id + 19, 'es_ES', NULL, '', ''),
(@max_id + 20, 'es_ES', NULL, '', ''),
(@max_id + 21, 'es_ES', NULL, '', ''),
(@max_id + 22, 'es_ES', NULL, '', ''),
(@max_id + 23, 'es_ES', NULL, '', ''),
(@max_id + 24, 'es_ES', NULL, '', ''),
(@max_id + 25, 'es_ES', NULL, '', ''),
(@max_id + 26, 'es_ES', NULL, '', ''),
(@max_id + 27, 'es_ES', NULL, '', ''),
(@max_id + 28, 'es_ES', NULL, '', ''),
(@max_id + 29, 'es_ES', NULL, '', ''),
(@max_id + 30, 'es_ES', NULL, '', ''),
(@max_id + 31, 'es_ES', NULL, '', ''),
(@max_id + 32, 'es_ES', NULL, '', ''),
(@max_id + 33, 'es_ES', NULL, '', ''),
(@max_id + 34, 'es_ES', NULL, '', ''),
(@max_id + 35, 'es_ES', NULL, '', ''),
(@max_id + 36, 'es_ES', NULL, '', ''),
(@max_id + 37, 'es_ES', NULL, '', ''),
(@max_id + 38, 'es_ES', NULL, '', ''),
(@max_id + 39, 'es_ES', NULL, '', ''),
(@max_id + 40, 'es_ES', NULL, '', ''),
(@max_id + 41, 'es_ES', NULL, '', ''),
(@max_id + 42, 'es_ES', NULL, '', ''),
(@max_id + 43, 'es_ES', NULL, '', ''),
(@max_id + 44, 'es_ES', NULL, '', ''),
(@max_id + 45, 'es_ES', NULL, '', ''),
(@max_id + 46, 'es_ES', NULL, '', ''),
(@max_id + 47, 'es_ES', NULL, '', ''),
(@max_id + 48, 'es_ES', NULL, '', ''),
(@max_id + 49, 'es_ES', NULL, '', ''),
(@max_id + 50, 'es_ES', NULL, '', ''),
(@max_id + 51, 'es_ES', NULL, '', ''),
(@max_id + 52, 'es_ES', NULL, '', ''),
(@max_id + 53, 'es_ES', NULL, '', ''),
(@max_id + 54, 'es_ES', NULL, '', ''),
(@max_id + 55, 'es_ES', NULL, '', ''),
(@max_id + 56, 'es_ES', NULL, '', ''),
(@max_id + 57, 'es_ES', NULL, '', ''),
(@max_id + 58, 'es_ES', NULL, '', ''),
(@max_id + 59, 'es_ES', NULL, '', ''),
(@max_id + 60, 'es_ES', NULL, '', ''),
(@max_id + 61, 'es_ES', NULL, '', ''),
(@max_id + 62, 'es_ES', NULL, '', ''),
(@max_id + 63, 'es_ES', NULL, '', ''),
(@max_id + 64, 'es_ES', NULL, '', ''),
(@max_id + 65, 'es_ES', NULL, '', ''),
(@max_id + 1, 'fr_FR', 'Profil - colonne tableau', '', ''),
(@max_id + 2, 'fr_FR', 'Profil - ligne du tableau', '', ''),
(@max_id + 3, 'fr_FR', 'Import - colonne tableau', '', ''),
(@max_id + 4, 'fr_FR', 'Import - ligne du tableau', '', ''),
(@max_id + 5, 'fr_FR', 'Export - colonne tableau', '', ''),
(@max_id + 6, 'fr_FR', 'Export - ligne du tableau', '', ''),
(@max_id + 7, 'fr_FR', 'Édition d\'une categorie - en haut', '', ''),
(@max_id + 8, 'fr_FR', 'Édition d\'une categorie - en bas', '', ''),
(@max_id + 9, 'fr_FR', 'Édition d\'une marque - en haut', '', ''),
(@max_id + 10, 'fr_FR', 'Édition d\'une marque - en bas', '', ''),
(@max_id + 11, 'fr_FR', 'Édition d\'une déclinaison - en haut', '', ''),
(@max_id + 12, 'fr_FR', 'Édition d\'une déclinaison - en bas', '', ''),
(@max_id + 13, 'fr_FR', 'Édition d\'une devise - en haut', '', ''),
(@max_id + 14, 'fr_FR', 'Édition d\'une devise - en bas', '', ''),
(@max_id + 15, 'fr_FR', 'Édition d\'un pays - en haut', '', ''),
(@max_id + 16, 'fr_FR', 'Édition d\'un pays - en bas', '', ''),
(@max_id + 17, 'fr_FR', 'Édition d\'un contenu - en haut', '', ''),
(@max_id + 18, 'fr_FR', 'Édition d\'un contenu - en bas', '', ''),
(@max_id + 19, 'fr_FR', 'Édition d\'une caractéristique - en haut', '', ''),
(@max_id + 20, 'fr_FR', 'Édition d\'une caractéristique - en bas', '', ''),
(@max_id + 21, 'fr_FR', 'Édition d\'un document - en haut', '', ''),
(@max_id + 22, 'fr_FR', 'Édition d\'un document - en bas', '', ''),
(@max_id + 23, 'fr_FR', 'Édition d\'un client - en haut', '', ''),
(@max_id + 24, 'fr_FR', 'Édition d\'un client - en bas', '', ''),
(@max_id + 25, 'fr_FR', 'Édition d\'image - en haut', '', ''),
(@max_id + 26, 'fr_FR', 'Édition d\'image - en bas', '', ''),
(@max_id + 27, 'fr_FR', 'Édition d\'hook - en haut', '', ''),
(@max_id + 28, 'fr_FR', 'Édition d\'hook - en bas', '', ''),
(@max_id + 29, 'fr_FR', 'Édition d\'un dossier - en haut', '', ''),
(@max_id + 30, 'fr_FR', 'Édition d\'un dossier - en bas', '', ''),
(@max_id + 31, 'fr_FR', 'Édition d\'un hook de module - en haut', '', ''),
(@max_id + 32, 'fr_FR', 'Édition d\'un hook de module - en bas', '', ''),
(@max_id + 33, 'fr_FR', 'Édition d\'un module - en haut', '', ''),
(@max_id + 34, 'fr_FR', 'Édition d\'un module - en bas', '', ''),
(@max_id + 35, 'fr_FR', 'Édition d\'un message - en haut', '', ''),
(@max_id + 36, 'fr_FR', 'Édition d\'un message - en bas', '', ''),
(@max_id + 37, 'fr_FR', 'Édition d\'un profil - en haut', '', ''),
(@max_id + 38, 'fr_FR', 'Édition d\'un profil - en bas', '', ''),
(@max_id + 39, 'fr_FR', 'Édition d\'un produit - en haut', '', ''),
(@max_id + 40, 'fr_FR', 'Édition d\'un produit - en bas', '', ''),
(@max_id + 41, 'fr_FR', 'Édition d\'une commande - en haut', '', ''),
(@max_id + 42, 'fr_FR', 'Édition d\'une commande - en bas', '', ''),
(@max_id + 43, 'fr_FR', 'Édition des zones de livraison d\'un transporteur - en haut', '', ''),
(@max_id + 44, 'fr_FR', 'Édition des zones de livraison d\'un transporteur - en bas', '', ''),
(@max_id + 45, 'fr_FR', 'Édition d\'une zone de livraison - en haut', '', ''),
(@max_id + 46, 'fr_FR', 'Édition d\'une zone de livraiso - en bas', '', ''),
(@max_id + 47, 'fr_FR', 'Édition d\'une promotion - en haut', '', ''),
(@max_id + 48, 'fr_FR', 'Édition d\'une promotion - en bas', '', ''),
(@max_id + 49, 'fr_FR', 'Édition d\'une variable - en haut', '', ''),
(@max_id + 50, 'fr_FR', 'Édition d\'une variable - en bas', '', ''),
(@max_id + 51, 'fr_FR', 'Édition d\'un gabarit - en haut', '', ''),
(@max_id + 52, 'fr_FR', 'Édition d\'un gabarit - en bas', '', ''),
(@max_id + 53, 'fr_FR', 'Édition d\'une règle de taxe - en haut', '', ''),
(@max_id + 54, 'fr_FR', 'Édition d\'une règle de taxe - en bas', '', ''),
(@max_id + 55, 'fr_FR', 'Édition d\'une taxe - en haut', '', ''),
(@max_id + 56, 'fr_FR', 'Édition d\'une taxe - en bas', '', ''),
(@max_id + 57, 'fr_FR', 'Édition d\'une commande - sous les informations du produit', '', ''),
(@max_id + 58, 'fr_FR', 'Commande- Onglet', '', ''),
(@max_id + 59, 'fr_FR', 'Détail d\'une commande - Après un produit', '', ''),
(@max_id + 60, 'fr_FR', 'Onglet SEO - en haut', '', ''),
(@max_id + 61, 'fr_FR', 'Onglet SEO - en bas', '', ''),
(@max_id + 62, 'fr_FR', 'Onglet image - en haut', '', ''),
(@max_id + 63, 'fr_FR', 'Onglet image - en bas', '', ''),
(@max_id + 64, 'fr_FR', 'Onglet document - en haut', '', ''),
(@max_id + 65, 'fr_FR', 'Onglet document - en bas', '', ''),
(@max_id + 1, 'it_IT', NULL, '', ''),
(@max_id + 2, 'it_IT', NULL, '', ''),
(@max_id + 3, 'it_IT', NULL, '', ''),
(@max_id + 4, 'it_IT', NULL, '', ''),
(@max_id + 5, 'it_IT', NULL, '', ''),
(@max_id + 6, 'it_IT', NULL, '', ''),
(@max_id + 7, 'it_IT', NULL, '', ''),
(@max_id + 8, 'it_IT', NULL, '', ''),
(@max_id + 9, 'it_IT', NULL, '', ''),
(@max_id + 10, 'it_IT', NULL, '', ''),
(@max_id + 11, 'it_IT', NULL, '', ''),
(@max_id + 12, 'it_IT', NULL, '', ''),
(@max_id + 13, 'it_IT', NULL, '', ''),
(@max_id + 14, 'it_IT', NULL, '', ''),
(@max_id + 15, 'it_IT', NULL, '', ''),
(@max_id + 16, 'it_IT', NULL, '', ''),
(@max_id + 17, 'it_IT', NULL, '', ''),
(@max_id + 18, 'it_IT', NULL, '', ''),
(@max_id + 19, 'it_IT', NULL, '', ''),
(@max_id + 20, 'it_IT', NULL, '', ''),
(@max_id + 21, 'it_IT', NULL, '', ''),
(@max_id + 22, 'it_IT', NULL, '', ''),
(@max_id + 23, 'it_IT', NULL, '', ''),
(@max_id + 24, 'it_IT', NULL, '', ''),
(@max_id + 25, 'it_IT', NULL, '', ''),
(@max_id + 26, 'it_IT', NULL, '', ''),
(@max_id + 27, 'it_IT', NULL, '', ''),
(@max_id + 28, 'it_IT', NULL, '', ''),
(@max_id + 29, 'it_IT', NULL, '', ''),
(@max_id + 30, 'it_IT', NULL, '', ''),
(@max_id + 31, 'it_IT', NULL, '', ''),
(@max_id + 32, 'it_IT', NULL, '', ''),
(@max_id + 33, 'it_IT', NULL, '', ''),
(@max_id + 34, 'it_IT', NULL, '', ''),
(@max_id + 35, 'it_IT', NULL, '', ''),
(@max_id + 36, 'it_IT', NULL, '', ''),
(@max_id + 37, 'it_IT', NULL, '', ''),
(@max_id + 38, 'it_IT', NULL, '', ''),
(@max_id + 39, 'it_IT', NULL, '', ''),
(@max_id + 40, 'it_IT', NULL, '', ''),
(@max_id + 41, 'it_IT', NULL, '', ''),
(@max_id + 42, 'it_IT', NULL, '', ''),
(@max_id + 43, 'it_IT', NULL, '', ''),
(@max_id + 44, 'it_IT', NULL, '', ''),
(@max_id + 45, 'it_IT', NULL, '', ''),
(@max_id + 46, 'it_IT', NULL, '', ''),
(@max_id + 47, 'it_IT', NULL, '', ''),
(@max_id + 48, 'it_IT', NULL, '', ''),
(@max_id + 49, 'it_IT', NULL, '', ''),
(@max_id + 50, 'it_IT', NULL, '', ''),
(@max_id + 51, 'it_IT', NULL, '', ''),
(@max_id + 52, 'it_IT', NULL, '', ''),
(@max_id + 53, 'it_IT', NULL, '', ''),
(@max_id + 54, 'it_IT', NULL, '', ''),
(@max_id + 55, 'it_IT', NULL, '', ''),
(@max_id + 56, 'it_IT', NULL, '', ''),
(@max_id + 57, 'it_IT', NULL, '', ''),
(@max_id + 58, 'it_IT', NULL, '', ''),
(@max_id + 59, 'it_IT', NULL, '', ''),
(@max_id + 60, 'it_IT', NULL, '', ''),
(@max_id + 61, 'it_IT', NULL, '', ''),
(@max_id + 62, 'it_IT', NULL, '', ''),
(@max_id + 63, 'it_IT', NULL, '', ''),
(@max_id + 64, 'it_IT', NULL, '', ''),
(@max_id + 65, 'it_IT', NULL, '', ''),
(@max_id + 1, 'pt_BR', NULL, '', ''),
(@max_id + 2, 'pt_BR', NULL, '', ''),
(@max_id + 3, 'pt_BR', NULL, '', ''),
(@max_id + 4, 'pt_BR', NULL, '', ''),
(@max_id + 5, 'pt_BR', NULL, '', ''),
(@max_id + 6, 'pt_BR', NULL, '', ''),
(@max_id + 7, 'pt_BR', NULL, '', ''),
(@max_id + 8, 'pt_BR', NULL, '', ''),
(@max_id + 9, 'pt_BR', NULL, '', ''),
(@max_id + 10, 'pt_BR', NULL, '', ''),
(@max_id + 11, 'pt_BR', NULL, '', ''),
(@max_id + 12, 'pt_BR', NULL, '', ''),
(@max_id + 13, 'pt_BR', NULL, '', ''),
(@max_id + 14, 'pt_BR', NULL, '', ''),
(@max_id + 15, 'pt_BR', NULL, '', ''),
(@max_id + 16, 'pt_BR', NULL, '', ''),
(@max_id + 17, 'pt_BR', NULL, '', ''),
(@max_id + 18, 'pt_BR', NULL, '', ''),
(@max_id + 19, 'pt_BR', NULL, '', ''),
(@max_id + 20, 'pt_BR', NULL, '', ''),
(@max_id + 21, 'pt_BR', NULL, '', ''),
(@max_id + 22, 'pt_BR', NULL, '', ''),
(@max_id + 23, 'pt_BR', NULL, '', ''),
(@max_id + 24, 'pt_BR', NULL, '', ''),
(@max_id + 25, 'pt_BR', NULL, '', ''),
(@max_id + 26, 'pt_BR', NULL, '', ''),
(@max_id + 27, 'pt_BR', NULL, '', ''),
(@max_id + 28, 'pt_BR', NULL, '', ''),
(@max_id + 29, 'pt_BR', NULL, '', ''),
(@max_id + 30, 'pt_BR', NULL, '', ''),
(@max_id + 31, 'pt_BR', NULL, '', ''),
(@max_id + 32, 'pt_BR', NULL, '', ''),
(@max_id + 33, 'pt_BR', NULL, '', ''),
(@max_id + 34, 'pt_BR', NULL, '', ''),
(@max_id + 35, 'pt_BR', NULL, '', ''),
(@max_id + 36, 'pt_BR', NULL, '', ''),
(@max_id + 37, 'pt_BR', NULL, '', ''),
(@max_id + 38, 'pt_BR', NULL, '', ''),
(@max_id + 39, 'pt_BR', NULL, '', ''),
(@max_id + 40, 'pt_BR', NULL, '', ''),
(@max_id + 41, 'pt_BR', NULL, '', ''),
(@max_id + 42, 'pt_BR', NULL, '', ''),
(@max_id + 43, 'pt_BR', NULL, '', ''),
(@max_id + 44, 'pt_BR', NULL, '', ''),
(@max_id + 45, 'pt_BR', NULL, '', ''),
(@max_id + 46, 'pt_BR', NULL, '', ''),
(@max_id + 47, 'pt_BR', NULL, '', ''),
(@max_id + 48, 'pt_BR', NULL, '', ''),
(@max_id + 49, 'pt_BR', NULL, '', ''),
(@max_id + 50, 'pt_BR', NULL, '', ''),
(@max_id + 51, 'pt_BR', NULL, '', ''),
(@max_id + 52, 'pt_BR', NULL, '', ''),
(@max_id + 53, 'pt_BR', NULL, '', ''),
(@max_id + 54, 'pt_BR', NULL, '', ''),
(@max_id + 55, 'pt_BR', NULL, '', ''),
(@max_id + 56, 'pt_BR', NULL, '', ''),
(@max_id + 57, 'pt_BR', NULL, '', ''),
(@max_id + 58, 'pt_BR', NULL, '', ''),
(@max_id + 59, 'pt_BR', NULL, '', ''),
(@max_id + 60, 'pt_BR', NULL, '', ''),
(@max_id + 61, 'pt_BR', NULL, '', ''),
(@max_id + 62, 'pt_BR', NULL, '', ''),
(@max_id + 63, 'pt_BR', NULL, '', ''),
(@max_id + 64, 'pt_BR', NULL, '', ''),
(@max_id + 65, 'pt_BR', NULL, '', ''),
(@max_id + 1, 'tr_TR', 'Profil - Tablo üstbilgisi', '', ''),
(@max_id + 2, 'tr_TR', 'Profil - tablo satırı', '', ''),
(@max_id + 3, 'tr_TR', 'İthalat - Tablo üstbilgisi', '', ''),
(@max_id + 4, 'tr_TR', 'İthalat - tablo satırı', '', ''),
(@max_id + 5, 'tr_TR', 'İthalat - Tablo üstbilgisi', '', ''),
(@max_id + 6, 'tr_TR', 'İhracat - tablo satırı', '', ''),
(@max_id + 7, 'tr_TR', 'Kategori Düzenle - üst', '', ''),
(@max_id + 8, 'tr_TR', 'Kategori Düzenle - alt', '', ''),
(@max_id + 9, 'tr_TR', 'Marka Düzenle - üst', '', ''),
(@max_id + 10, 'tr_TR', 'Düzenle marka - alt', '', ''),
(@max_id + 11, 'tr_TR', 'Öznitelik Düzenle - üst', '', ''),
(@max_id + 12, 'tr_TR', 'Öznitelik Düzenle - alt', '', ''),
(@max_id + 13, 'tr_TR', 'Para birimi Düzenle - üst', '', ''),
(@max_id + 14, 'tr_TR', 'Para birimi Düzenle - alt', '', ''),
(@max_id + 15, 'tr_TR', 'Ülke Düzenle - üst', '', ''),
(@max_id + 16, 'tr_TR', 'Ülke düzenleme - alt', '', ''),
(@max_id + 17, 'tr_TR', 'İçerik düzenleme - üst', '', ''),
(@max_id + 18, 'tr_TR', 'Düzenleme içerik - alt', '', ''),
(@max_id + 19, 'tr_TR', 'Özelliği Düzenle - üst', '', ''),
(@max_id + 20, 'tr_TR', 'Düzenleme özelliği - alt', '', ''),
(@max_id + 21, 'tr_TR', 'Belge düzenleme - üst', '', ''),
(@max_id + 22, 'tr_TR', 'Belge düzenleme - alt', '', ''),
(@max_id + 23, 'tr_TR', 'İstemci Düzenle - üst', '', ''),
(@max_id + 24, 'tr_TR', 'İstemci Düzenle - alt', '', ''),
(@max_id + 25, 'tr_TR', 'Görüntü Düzenle - üst', '', ''),
(@max_id + 26, 'tr_TR', 'Görüntü Düzenle - alt', '', ''),
(@max_id + 27, 'tr_TR', 'Kanca Düzenle - üst', '', ''),
(@max_id + 28, 'tr_TR', 'Düzenle kanca - alt', '', ''),
(@max_id + 29, 'tr_TR', 'Klasörü Düzenle - üst', '', ''),
(@max_id + 30, 'tr_TR', 'Klasörünü düzenlemek - alt', '', ''),
(@max_id + 31, 'tr_TR', 'Modülü kanca Düzenle - üst', '', ''),
(@max_id + 32, 'tr_TR', 'Modülü kanca Düzenle - alt', '', ''),
(@max_id + 33, 'tr_TR', 'Modülü Düzenle - üst', '', ''),
(@max_id + 34, 'tr_TR', 'Modülü Düzenle - alt', '', ''),
(@max_id + 35, 'tr_TR', 'İleti düzenleme - üst', '', ''),
(@max_id + 36, 'tr_TR', 'Düzenle mesaj - alt', '', ''),
(@max_id + 37, 'tr_TR', 'Profil Düzenle - üst', '', ''),
(@max_id + 38, 'tr_TR', 'Düzenle Profil - alt', '', ''),
(@max_id + 39, 'tr_TR', 'Ürün Düzenle - üst', '', ''),
(@max_id + 40, 'tr_TR', 'Ürün Düzenle - alt', '', ''),
(@max_id + 41, 'tr_TR', 'Sipariş Düzenle - üst', '', ''),
(@max_id + 42, 'tr_TR', 'Düzenleme sipariş - alt', '', ''),
(@max_id + 43, 'tr_TR', 'Nakliye bölgeleri Düzenle - üst', '', ''),
(@max_id + 44, 'tr_TR', 'Nakliye bölgeleri düzenlemek - alt', '', ''),
(@max_id + 45, 'tr_TR', 'Sevkiyat yapılandırma Düzenle - üst', '', ''),
(@max_id + 46, 'tr_TR', 'Aktarma yapılandırması Düzenle - alt', '', ''),
(@max_id + 47, 'tr_TR', 'Satılık düzen - en iyi', '', ''),
(@max_id + 48, 'tr_TR', 'Satılık Düzenle - alt', '', ''),
(@max_id + 49, 'tr_TR', 'Değişken Düzenle - üst', '', ''),
(@max_id + 50, 'tr_TR', 'Değişkenini Düzenle - alt', '', ''),
(@max_id + 51, 'tr_TR', 'Şablonu Düzenle - üst', '', ''),
(@max_id + 52, 'tr_TR', 'Şablonu Düzenle - alt', '', ''),
(@max_id + 53, 'tr_TR', 'Kdv Kural Düzenle - üst', '', ''),
(@max_id + 54, 'tr_TR', 'Kural düzenleme Kdv - alt', '', ''),
(@max_id + 55, 'tr_TR', 'Kdv Düzenle - üst', '', ''),
(@max_id + 56, 'tr_TR', 'Düzenleme Kdvi - alt', '', ''),
(@max_id + 57, 'tr_TR', 'Sonra ürün bilgileri görüntülenen sipariş Düzenle-', '', ''),
(@max_id + 58, 'tr_TR', 'Sipariş - sekmesi', '', ''),
(@max_id + 59, 'tr_TR', 'Sipariş ayrıntıları - ürün sonra', '', ''),
(@max_id + 60, 'tr_TR', 'Sekme SEO - üst', '', ''),
(@max_id + 61, 'tr_TR', 'SEO sekme - alt', '', ''),
(@max_id + 62, 'tr_TR', 'Sekme resmi - üst', '', ''),
(@max_id + 63, 'tr_TR', 'Resim sekmesi - alt', '', ''),
(@max_id + 64, 'tr_TR', 'Sekmesini belge - üst', '', ''),
(@max_id + 65, 'tr_TR', 'Belge sekmesi - alt', '', '')
;

-- Fix attribute_template and feature_template relations
ALTER TABLE `attribute_template` DROP FOREIGN KEY `fk_attribute_template`; ALTER TABLE `attribute_template` ADD CONSTRAINT `fk_attribute_template` FOREIGN KEY (`template_id`) REFERENCES `template`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;
ALTER TABLE `feature_template` DROP FOREIGN KEY `fk_feature_template`; ALTER TABLE `feature_template` ADD CONSTRAINT `fk_feature_template` FOREIGN KEY (`template_id`) REFERENCES `template`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS = 1;