<?php
namespace Thelia\Coupon;

use InvalidArgumentException;
use Thelia\Coupon\Parameter\DateParam;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-19 at 18:26:01.
 */
class DateParamTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\DateParam::compareTo
     *
     */
    public function testInferiorDate()
    {
        $dateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-07-07");

        $dateParam = new DateParam($dateValidator);

        $expected = 1;
        $actual = $dateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\DateParam::compareTo
     *
     */
    public function testEquelsDate()
    {
        $dateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-07-08");

        $dateParam = new DateParam($dateValidator);

        $expected = 0;
        $actual = $dateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\DateParam::compareTo
     *
     */
    public function testSuperiorDate()
    {
        $dateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-07-09");

        $dateParam = new DateParam($dateValidator);

        $expected = -1;
        $actual = $dateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Thelia\Coupon\Parameter\DateParam::compareTo
     * @expectedException InvalidArgumentException
     */
    public function testInvalidArgumentException()
    {
        $dateValidator = new \DateTime("2012-07-08");
        $dateToValidate = 1377012588;

        $dateParam = new DateParam($dateValidator);

        $dateParam->compareTo($dateToValidate);
    }



    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
