<?php
namespace Thelia\Coupon;

use InvalidArgumentException;
use Symfony\Component\Intl\Exception\NotImplementedException;
use Thelia\Coupon\Parameter\RepeatedDateParam;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-19 at 18:26:01.
 */
class RepeatedDateParamTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testInferiorDate()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-07-07");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth();

        $expected = -1;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryMonthOneTimeFirstPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-07-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth();

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryMonthOneTimeSecondPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-08-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth();

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryMonthTenTimesThirdPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-09-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(1, 10);

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryMonthTenTimesTensPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2013-05-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(1, 10);

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryFourMonthTwoTimesSecondPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-11-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testEqualsDateRepeatEveryFourMonthTwoTimesLastPeriod()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2013-03-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $expected = 0;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testNotEqualsDateRepeatEveryFourMonthTwoTimes1()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-08-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $expected = -1;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testNotEqualsDateRepeatEveryFourMonthTwoTimes2()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2012-12-08");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $expected = -1;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     *
     * @covers Thelia\Coupon\Parameter\RepeatedDateParam::compareTo
     *
     */
    public function testSuperiorDateRepeatEveryFourMonthTwoTimes()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = new \DateTime("2013-03-09");

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $expected = -1;
        $actual = $repeatedDateParam->compareTo($dateToValidate);
        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers Thelia\Coupon\Parameter\DateParam::compareTo
     * @expectedException InvalidArgumentException
     */
    public function testInvalidArgumentException()
    {
        $startDateValidator = new \DateTime("2012-07-08");
        $dateToValidate = 1377012588;

        $repeatedDateParam = new RepeatedDateParam();
        $repeatedDateParam->setFrom($startDateValidator);
        $repeatedDateParam->repeatEveryMonth(4, 2);

        $repeatedDateParam->compareTo($dateToValidate);
    }



    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
