<?php

declare(strict_types=1);

/*
 * This file is part of the Thelia package.
 * http://www.thelia.net
 *
 * (c) OpenStudio <info@thelia.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Thelia\Tests\Integration\Action;

use Thelia\Core\Event\Order\OrderEvent;
use Thelia\Core\Event\TheliaEvents;
use Thelia\Model\OrderQuery;
use Thelia\Model\OrderStatusQuery;
use Thelia\Test\ActionIntegrationTestCase;

final class OrderActionTest extends ActionIntegrationTestCase
{
    public function testUpdateStatusChangesStatusId(): void
    {
        $order = $this->factory->order();
        $paidStatus = OrderStatusQuery::create()->findOneByCode('paid');
        self::assertNotNull($paidStatus);

        $event = new OrderEvent($order);
        $event->setStatus($paidStatus->getId());
        $this->dispatch($event, TheliaEvents::ORDER_UPDATE_STATUS);

        self::assertSame($paidStatus->getId(), OrderQuery::create()->findPk($order->getId())->getStatusId());
    }

    public function testUpdateDeliveryRefPersistsTheGivenReference(): void
    {
        $order = $this->factory->order();

        $event = new OrderEvent($order);
        $event->setDeliveryRef('TRACK-12345');
        $this->dispatch($event, TheliaEvents::ORDER_UPDATE_DELIVERY_REF);

        self::assertSame(
            'TRACK-12345',
            OrderQuery::create()->findPk($order->getId())->getDeliveryRef(),
        );
    }

    public function testFactoryAssignsAutoGeneratedRef(): void
    {
        $order = $this->factory->order();

        self::assertMatchesRegularExpression('/^ORD/', $order->getRef());
    }
}
